### ISSUE TITLE
bug(python): table can't be opened in azure storage

### ISSUE THREAD

**Issue by ericfeunekes** [lancedb/lancedb#1072]
### LanceDB version

v0.6.2

### What happened?

Followed the instructions [here](https://lancedb.github.io/lancedb/guides/storage/#azure-blob-storage) to connect to azure blob storage. I set the required environment variables and connected to the database. I was able to see the correct tables using `db.table_names()` so I know the connection was successful.

When I tried `db.open_table` for the listed tables I got the following error:

```python
ArrowInvalid                              Traceback (most recent call last)
File <command-18817827359282>, line 1
----> 1 all_table = db.open_table("all_content")

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-7201c84b-5d15-4c4f-b92d-1e96b0358490/lib/python3.10/site-packages/lancedb/db.py:417, in LanceDBConnection.open_table(self, name)
    404 @override
    405 def open_table(self, name: str) -> LanceTable:
    406     """Open a table in the database.
    407 
    408     Parameters
   (...)
    415     A LanceTable object representing the table.
    416     """
--> 417     return LanceTable.open(self, name)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-7201c84b-5d15-4c4f-b92d-1e96b0358490/lib/python3.10/site-packages/lancedb/table.py:838, in LanceTable.open(cls, db, name, **kwargs)
    835 @classmethod
    836 def open(cls, db, name, **kwargs):
    837     tbl = cls(db, name, **kwargs)
--> 838     fs, path = fs_from_uri(tbl._dataset_uri)
    839     file_info = fs.get_file_info(path)
    840     if file_info.type != pa.fs.FileType.Directory:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-7201c84b-5d15-4c4f-b92d-1e96b0358490/lib/python3.10/site-packages/lancedb/util.py:95, in fs_from_uri(uri)
     92     path = get_uri_location(uri)
     93     return fs, path
---> 95 return pa_fs.FileSystem.from_uri(uri)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-7201c84b-5d15-4c4f-b92d-1e96b0358490/lib/python3.10/site-packages/pyarrow/_fs.pyx:471, in pyarrow._fs.FileSystem.from_uri()

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-7201c84b-5d15-4c4f-b92d-1e96b0358490/lib/python3.10/site-packages/pyarrow/error.pxi:154, in pyarrow.lib.pyarrow_internal_check_status()

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-7201c84b-5d15-4c4f-b92d-1e96b0358490/lib/python3.10/site-packages/pyarrow/error.pxi:91, in pyarrow.lib.check_status()
```

`pyarrow == 15.0.0` is installed.

**Comment by rcdilorenzo** [comment]
Looks like this is also noted in #485. @westonpace, were any of the read commands ever working for azure? I see that logic for reading in lancedb-python has special logic for S3 and pyarrow.fs doesn't support azure. I've got a concrete use case for a product of ours that I'm performance testing before we use this but the azure support for reading is a blocker. If the support is there soon, we'd love to use this in production. 🤩

**Comment by ericfeunekes** [comment]
> If the support is there soon, we'd love to use this in production ASAP

Same here. I'm testing LanceDB in dev by accessing it from a volume in Databricks to load data (which requires a full copy/overwrite of the lance files each time) and mounting the container in an Azure Web App so that langchain can access lance from the "local" filesystem. Problem is I'm seeing massive latency on reads for both cases.

In Databricks when reading from a lance table that is stored in a volume (adls gen2 standard) I'm seeing 2-3 minutes of latency per search. In the Web App I'm getting p95 latency of around 12 seconds. Obviously neither of these will work in production. When I move the table to the local filesystem the latency drops to sub-100ms range that I expect from an unindexed table. 

This is all to say that I was hoping to use the `az://` filesystem to get around these latency issues so I'm really hoping it's fixed soon if possible!

**Comment by westonpace** [comment]
I believe this support will improve once we finish migrating the python SDK on top of the rust SDK.  This is something that is actively being worked on (e.g. https://github.com/lancedb/lancedb/pull/1052, https://github.com/lancedb/lancedb/pull/1070).  It will probably be available as part of a new, asynchronous, python API first.  Once we work out any initial bugs we will then migrate the synchronous API on top of the async API.

**Comment by 1jamesthompson1** [comment]
I am having a similiar issue.
My lancedb version is 0.8.2
With adlfs installed and is 2024.4.1

Creation of table seems to work fine:
```python
db = lancedb.connect('az://vectordb/testing_sync')

db.create_table('safety_issue_embeddings', safety_issues_embeddings, mode="overwrite")
```

> [2024-06-26T23:05:17Z WARN  lance::dataset] No existing dataset at az://vectordb/testing_sync/safety_issue_embeddings.lance, it will be created
> LanceTable(connection=LanceDBConnection(az://vectordb/testing_sync), name="safety_issue_embeddings")

Yet when I when I try to open the table or even just look at table names it fails.

```python
db.table_names()
```

> {
> 	"name": "ArrowInvalid",
> 	"message": "Unrecognized filesystem type in URI: az://vectordb/testing_sync/safety_issue_embeddings.lance",
> 	"stack": "---------------------------------------------------------------------------
> ArrowInvalid                              Traceback (most recent call last)
> Cell In[30], line 1
> ----> 1 db.open_table('safety_issue_embeddings')
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/lancedb/db.py:446, in LanceDBConnection.open_table(self, name, index_cache_size)
>     431 @override
>     432 def open_table(
>     433     self, name: str, *, index_cache_size: Optional[int] = None
>     434 ) -> LanceTable:
>     435     \"\"\"Open a table in the database.
>     436 
>     437     Parameters
>    (...)
>     444     A LanceTable object representing the table.
>     445     \"\"\"
> --> 446     return LanceTable.open(self, name, index_cache_size=index_cache_size)
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/lancedb/table.py:915, in LanceTable.open(cls, db, name, **kwargs)
>     912 @classmethod
>     913 def open(cls, db, name, **kwargs):
>     914     tbl = cls(db, name, **kwargs)
> --> 915     fs, path = fs_from_uri(tbl._dataset_uri)
>     916     file_info = fs.get_file_info(path)
>     917     if file_info.type != pa.fs.FileType.Directory:
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/lancedb/util.py:120, in fs_from_uri(uri)
>     117     path = get_uri_location(uri)
>     118     return fs, path
> --> 120 return pa_fs.FileSystem.from_uri(uri)
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/pyarrow/_fs.pyx:471, in pyarrow._fs.FileSystem.from_uri()
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/pyarrow/error.pxi:154, in pyarrow.lib.pyarrow_internal_check_status()
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/pyarrow/error.pxi:91, in pyarrow.lib.check_status()
> 
> ArrowInvalid: Unrecognized filesystem type in URI: az://vectordb/testing_sync/safety_issue_embeddings.lance"
> }

```python
si_table = db.open_table('safety_issue_embeddings')
```

> {
> 	"name": "ArrowInvalid",
> 	"message": "Unrecognized filesystem type in URI: az://vectordb/testing/safety_issue_embeddings.lance",
> 	"stack": "---------------------------------------------------------------------------
> ArrowInvalid                              Traceback (most recent call last)
> Cell In[26], line 1
> ----> 1 si_table = db.open_table('safety_issue_embeddings')
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/lancedb/db.py:446, in LanceDBConnection.open_table(self, name, index_cache_size)
>     431 @override
>     432 def open_table(
>     433     self, name: str, *, index_cache_size: Optional[int] = None
>     434 ) -> LanceTable:
>     435     \"\"\"Open a table in the database.
>     436 
>     437     Parameters
>    (...)
>     444     A LanceTable object representing the table.
>     445     \"\"\"
> --> 446     return LanceTable.open(self, name, index_cache_size=index_cache_size)
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/lancedb/table.py:915, in LanceTable.open(cls, db, name, **kwargs)
>     912 @classmethod
>     913 def open(cls, db, name, **kwargs):
>     914     tbl = cls(db, name, **kwargs)
> --> 915     fs, path = fs_from_uri(tbl._dataset_uri)
>     916     file_info = fs.get_file_info(path)
>     917     if file_info.type != pa.fs.FileType.Directory:
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/lancedb/util.py:120, in fs_from_uri(uri)
>     117     path = get_uri_location(uri)
>     118     return fs, path
> --> 120 return pa_fs.FileSystem.from_uri(uri)
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/pyarrow/_fs.pyx:471, in pyarrow._fs.FileSystem.from_uri()
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/pyarrow/error.pxi:154, in pyarrow.lib.pyarrow_internal_check_status()
> 
> File ~/.cache/pypoetry/virtualenvs/taic-report-engine-vkGeZcZ8-py3.11/lib/python3.11/site-packages/pyarrow/error.pxi:91, in pyarrow.lib.check_status()
> 
> ArrowInvalid: Unrecognized filesystem type in URI: az://vectordb/testing/safety_issue_embeddings.lance"
> }

**Comment by ericthomas1** [comment]
What is the status of this bug? Can we use Azure Blob Storage + LanceDB?

**Comment by wjones127** [comment]
Yes, if you use the async API, it works. The sync API doesn't yet fully work, but will be fixed later once it's upgraded to being a wrapper around the sync API.

**Comment by elsell** [comment]
Any update on sync API support of `az://` filesystem?

**Comment by wjones127** [comment]
> Any update on sync API support of `az://` filesystem?

Haven't worked on this yet, but I expect to get to work on it before the end of the year.

**Comment by elsell** [comment]
> > Any update on sync API support of `az://` filesystem?
> 
> Haven't worked on this yet, but I expect to get to work on it before the end of the year.

Thank you for the quick response!

Interestingly enough, I was able to get a minimal example working by including `AZURE_STORAGE_CONNECTION_STRING` along with the account name and key. Note that the only change for me was adding the connection string to the environment:

```python
import lancedb
import os

os.environ["AZURE_STORAGE_ACCOUNT_NAME"] = "<storage_account_name>"
os.environ["AZURE_STORAGE_ACCOUNT_KEY"] = "<storage_account_key>"
os.environ["AZURE_ENDPOINT"] = "https://<endpoint>" # Optional if not connecting from enterprise environment.

# Even though most of the data in the connection string is duplicated by the vars above, 
# it still was necessary in my case to successfully connect.
os.environ["AZURE_STORAGE_CONNECTION_STRING"] = \
    "DefaultEndpointsProtocol=https;AccountName=<storage_account_name>;AccountKey=<key>;EndpointSuffix=<suffix>"

# Create a connection, using `az://` prefix
conn = lancedb.connect("az://my-bucket/lance-data")

# Create a table with some test data
conn.create_table("my-table", [{"test": 1234}])

# Open the table and add another column to test write operations
table = db.open_table("my-table")
table.add_columns({"second_col": "''"})

# Finally, print out the data in the table
print(table.search().to_list())
```

**Comment by erensahins** [comment]
Hi, we are very interested in using lancedb on azure with the sync client. Any updates on this work?

**Comment by MarkusPorti** [comment]
Is there an update on this?

I have the same issue, but with the asynchron client.
```python
logger.info("Initialize Vector-Database")
db = await connect_async("az://lancedb/test")
logger.debug("Connected to Vector-Database. Tables: %s", await db.table_names())
article_table = await db.open_table("products")
```
This code results in this output:
```logs
2024-12-11 09:58:59 - lva.main        [  INFO  ] Initialize Vector-Database
2024-12-11 09:58:59 - lva.main        [ DEBUG  ] Connected to Vector-Database. Tables: ['my_table', 'products', 'tbl', 'test']
2024-12-11 09:58:59 - uvicorn.error   [ ERROR  ] Traceback (most recent call last):
  [...]
  File "...\main.py", line 27, in lifespan
    article_table = await db.open_table("products")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\lancedb\db.py", line 810, in open_table
    table = await self._inner.open_table(name, storage_options, index_cache_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Table 'products' was not found
```

One can clearly see, that the table "products" exists as it is returned by `db.table_names()`

---
This error also only happens when I try to run my app locally.
When executing it in a Docker-Container it works fine.
But for developing it would be awesome if it would work in my venv too.

**Comment by wjones127** [comment]
Thanks for reporting that. It looks like there might be some bug in `open_table()`.

We are consolidating the async and sync APIs, so soon they will have the same implementation.

It looks like if we want to do some testing in CI, we could use Azurite: https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio%2Cblob-storage

I'll see if I can get this work prioritized. If you are able to diagnose the underlying issue, feel free to post an update in here.

**Comment by MarkusPorti** [comment]
@wjones127 Thank you very much for your effort!

Sadly I have no news on the reason for this.


While evaluating with a colleague we found that it works on his Mac and inside a Docker Container (Linux), but not directly on my Windows 11 machine.
We both tested the program after installing fresh dependencies with Poetry.
I attached the Poetry project and lock file for you (just remove the .txt extention):
[poetry.lock.txt](https://github.com/user-attachments/files/18102485/poetry.lock.txt)
[pyproject.toml.txt](https://github.com/user-attachments/files/18102486/pyproject.toml.txt)
Maybe this could hint you in the right direction.

**Comment by MarkusPorti** [comment]
@wjones127 I have a new suspicion about this issue.
It could be a problem with **building the url** of the NativeTable.

I tested some things like creating a new Table an how it looks like on Azure Storage.
This is my Database-Connection:
```python
await lancedb.connect_async("az://lancedb/test")
```
This is my new Table:
```python
await db.create_table("/articles", data=[{"name": "Test", "gewicht": 2}])
```
In a Jupyter-Notebook the output of the `create_table` is this:
```
NativeTable(articles, uri=az://lancedb/test\articles.lance?, read_consistency_interval=None)
```

I wondered why there is a Backslash instead of a slash in the URL and an Question-Mark at the end.
When looking inside my Azure-Storage the new Table was created outside the test-Directory and got an escaped Character in its name: 
![image](https://github.com/user-attachments/assets/02877d98-d4c9-4a3d-b81d-f3aaf8640bba)

While my previous created tables are inside the Directory `test:`
![image](https://github.com/user-attachments/assets/63f4c636-9c97-40f3-82e9-d29c41ef9808)

The newly created Table also won't be listed with the `db.table_names()` Method. I assume this just looks inside this directory for lance-Folders and therefore doesn't find the new one.

I hope this helps to patch this bug soon.

**Comment by MarkusPorti** [comment]
Another update:
When writing a Slash at the end of the database-connection-string it works!

```python
await lancedb.connect_async("az://lancedb/test/")
```

**Comment by Xuanwo** [comment]
Hi, this issue is invalid because Azure blob read support for the sync API was already fixed by PR #1102 (merged): fs_from_uri now handles the az:// scheme via adlfs, so tables can be opened from Azure storage. I'm closing this now. Feel free to create a new issue if the problem still exists.
