### ISSUE TITLE
bug(python): creating a table with a generator function gives strange error if no schema specified

### ISSUE THREAD

**Issue by westonpace** [lancedb/lancedb#1353]
### LanceDB version

v0.8.1

### What happened?

Using the async python code I tried to create a table using a generator but forgot to specify the schema.  The error I received was:

```
Traceback (most recent call last):
  File "/home/pace/dev/lance-experiments/v2-beta/mass_ingest.py", line 44, in <module>
    asyncio.run(main())
  File "/home/pace/miniconda3/envs/lancedb/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/pace/miniconda3/envs/lancedb/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pace/miniconda3/envs/lancedb/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/pace/dev/lance-experiments/v2-beta/mass_ingest.py", line 38, in main
    await db.create_table("images", load_images(batch_size))
  File "/home/pace/dev/lancedb/python/python/lancedb/db.py", line 758, in create_table
    validate_schema(schema)
  File "/home/pace/dev/lancedb/python/python/lancedb/common.py", line 116, in validate_schema
    if schema.metadata is not None:
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'metadata'
```

This is a non-obvious error

### Are there known steps to reproduce?

```
# Haven't tested this but it should be roughly correct
import lancedb
import pyarrow as pa

async def main():
    db = await lancedb.connect_async("/tmp/foo")
    def make_data():
        yield pa.table({"x": [1, 2, 3]})
    db.create_table("foo", make_data())
```

**Comment by eddyxu** [comment]
Verified, this is not an issue anymore.
