### ISSUE TITLE
Incremental data indexing mode

### ISSUE THREAD

**Issue by wpjgit** [lancedb/lancedb#1502]
### Description

After a full index is created for a new dataset, how to update the index for new data? What is the recommended method?
@w

**Comment by wjones127** [comment]
The operation you are looking for is `table.optimize`: https://lancedb.github.io/lancedb/python/python/#lancedb.table.AsyncTable.optimize

> Index: Optimizes the indices, adding new data to existing indices

**Comment by wpjgit** [comment]
use table.optimize, but failed to executed
Traceback (most recent call last):
  File "/opt/software/lancedb/benchmark_wpj/optimize_index_v1_1M.py", line 497, in <module>
    asyncio.run(optimize_test('/opt/dii/lance', 'dbpedia-entities-openai-1M'))
  File "/root/miniconda3/envs/lancedb_benchmark/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/miniconda3/envs/lancedb_benchmark/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/software/lancedb/benchmark_wpj/optimize_index_v1_1M.py", line 493, in optimize_test
    await optimize(uri, name)
  File "/opt/software/lancedb/benchmark_wpj/optimize_index_v1_1M.py", line 480, in optimize
    await table.optimize(cleanup_older_than=timedelta())
  File "/root/miniconda3/envs/lancedb_benchmark/lib/python3.10/site-packages/lancedb/table.py", line 2456, in optimize
    return await self._inner.optimize(cleanup_older_than)
RuntimeError: lance error: LanceError(IO): PlainDecoder: request([0..3383]) out of range: [0..3382], /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-io-0.15.0/src/encodings/plain.rs:262:17

**Comment by wpjgit** [comment]
index info：

>>> async def print_indices(uri: str, name: str):
...     async_db = await lancedb.connect_async(uri)
...     table = await async_db.open_table(name)
...     indices = await table.list_indices()
...     for index in indices:
...         print("column: " + index.columns[0] + ", index_type=" + index.index_type)
... 
>>> 
>>> asyncio.run(print_indices('/opt/dii/lance', 'dbpedia-entities-openai-1M'))
column: title, index_type=BTree
column: openai, index_type=IvfPq

**Comment by wjones127** [comment]
Given the error points to `lance-io/src/encodings/plain.rs`, this seems to be a problem with the V1 format in both cases. Which either means that the second case isn't actually in V1 or that it's an issue with the BTree index which is always in V1. (Or maybe IvfPQ is also in V1 right now, I'm not sure.)

I tried to reproduce this just now, but wasn't able to.

Here's what I tried:

1. Create a table with vector data and scalar data, using V2 file format
2. Create a vector index
3. Create a BTree index
4. Append new data
5. Run `table.optimize()`

This ran without error. Could you try modifying the script so you are able to reproduce the issue?

<details><summary>Attempted repro</summary>
<p>

```python
import lancedb
import pyarrow as pa
import pyarrow.compute as pc

# Create a vector dataset
dims = 128
nrows = 10_000
inner_vector = pc.cast(pc.random(nrows * dims), pa.float32())
vector = pa.FixedSizeListArray.from_arrays(inner_vector, dims)
table = pa.table({
    "vector": vector,
    "id": range(nrows),
})

db = await lancedb.connect_async("test")
table = await db.create_table("vector", table, mode="overwrite", use_legacy_format=False)

await table.create_index("vector")
await table.create_index("id")

# Add new data
new_vec_values = pc.cast(pc.random(nrows * dims), pa.float32())
new_data = pa.table({
    "vector": pa.FixedSizeListArray.from_arrays(new_vec_values, dims),
    "id": range(nrows, nrows * 2),
})
await table.add(new_data)

stats = await table.optimize()
stats
```

</p>
</details>

**Comment by wpjgit** [comment]
sorry. the index type I created is IVF_HNSW_PQ，The dataset used is https://huggingface.co/datasets/KShivendu/dbpedia-entities-openai-1M. and I found other error message.

Use the 'train-00000-of-00026-3c7b99d1c7eda36e.parquet' and 'train-00002-of-00026-b05ce48965853dad.parquet' files in the data set to write the lance.

1. data is written to one lance file.

>>> schema = pa.schema([pa.field("_id", pa.string()),
...                     pa.field("title", pa.string()),
...                     pa.field("text", pa.string()),
...                     pa.field("openai", pa.list_(pa.float32(), list_size=1536))])
>>> db = lancedb.connect('/opt/test/lance')
>>> table = db.create_table(name='test-optimize-1', schema=schema)
>>> 
>>> df = pd.read_parquet('./train-00000-of-00026-3c7b99d1c7eda36e.parquet')
>>> df1 = pd.read_parquet('./train-00001-of-00026-b05ce48965853dad.parquet')
>>> df2 = pd.concat([df, df1])
>>> table.add(df2)
>>> 
>>> table.create_index(vector_column_name="openai", index_type="IVF_HNSW_PQ")

>>> async def optimize_test():
...     async_db = await lancedb.connect_async('/opt/test/lance')
...     table = await async_db.open_table(name='test-optimize-1')
...     await table.optimize(cleanup_older_than=timedelta())
... 
>>> asyncio.run(optimize_test())

Error: RuntimeError: lance error: LanceError(Index): optimizing vector index: the sub index isn't PQ or HNSW, /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.15.0/src/index/vector/ivf.rs:322:23

2. Data is written to two lance files.

>>> schema = pa.schema([pa.field("_id", pa.string()),
...                     pa.field("title", pa.string()),
...                     pa.field("text", pa.string()),
...                     pa.field("openai", pa.list_(pa.float32(), list_size=1536))])
>>> db = lancedb.connect('/opt/test/lance')
>>> table = db.create_table(name='test-optimize-1', schema=schema)
>>> 
>>> df = pd.read_parquet('./train-00000-of-00026-3c7b99d1c7eda36e.parquet')
>>> df1 = pd.read_parquet('./train-00001-of-00026-b05ce48965853dad.parquet')
>>> table.add(df)
>>> table.add(df1)
>>> 
>>> table.create_index(vector_column_name="openai", index_type="IVF_HNSW_PQ")

>>> async def optimize_test():
...     async_db = await lancedb.connect_async('/opt/test/lance')
...     table = await async_db.open_table(name='test-optimize-1')
...     await table.optimize(cleanup_older_than=timedelta())
... 
>>> asyncio.run(optimize_test())

Error: RuntimeError: lance error: LanceError(IO): PlainDecoder: request([0..316]) out of range: [0..315], /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-io-0.15.0/src/encodings/plain.rs:262:17

**Comment by wjones127** [comment]
Thanks for the reproductions. I can reproduce the errors with them.

They are a bit odd examples, though, since you are applying optimize to an index that was just created. It should already be optimal at that point, so this would be a no-op anyways.

Here are self-contained versions that don't require download:

## Optimize on new table

```python
import lancedb
import pyarrow as pa
import pyarrow.compute as pc

# Create a vector dataset
dims = 128
nrows = 10_000
inner_vector = pc.cast(pc.random(nrows * dims), pa.float32())
vector = pa.FixedSizeListArray.from_arrays(inner_vector, dims)
data = pa.table({
    "vector": vector,
    "id": range(nrows),
})

db = lancedb.connect('test')
db.drop_table('test-optimize-1')
table = db.create_table(name='test-optimize-1', schema=data.schema)

table.add(data)

table.create_index(vector_column_name="vector", index_type="IVF_HNSW_PQ", num_sub_vectors=32)

async_db = await lancedb.connect_async('test')
table = await async_db.open_table('test-optimize-1')
await table.optimize()
```

I wasn't able to reproduce this at the Lance level, so it might be that LanceDB is passing down the wrong parameters.

## Optimize on two files

```python
import lancedb
import pyarrow as pa
import pyarrow.compute as pc

# Create a vector dataset
dims = 128
nrows = 10_000
inner_vector = pc.cast(pc.random(nrows * dims), pa.float32())
vector = pa.FixedSizeListArray.from_arrays(inner_vector, dims)
data = pa.table({
    "vector": vector,
    "id": range(nrows),
})

db = lancedb.connect('test')
db.drop_table('test-optimize-1')
table = db.create_table(name='test-optimize-1', schema=data.schema)

table.add(data)
table.add(data)

table.create_index(vector_column_name="vector", index_type="IVF_HNSW_PQ", num_sub_vectors=32)

async_db = await lancedb.connect_async('test')
table = await async_db.open_table('test-optimize-1')
await table.optimize()
```

@BubbleCal could you take a look when you have a chance?

**Comment by wpjgit** [comment]
I executed the command to create an index (IVF_PQ) on a 40 million dataset, which took 624.80 seconds. After that, I added a piece of data and executed the optimize command(it works), which took 612.59 seconds. What is the difference between the two methods in adding new data to an existing index? I want to add new data to the index in the shortest possible time.

**Comment by wpjgit** [comment]
I'm not sure if I'm using it wrong, or if lance doesn't have the ability.

**Comment by BubbleCal** [comment]
We missed to support `optimize` when adding `IVF_HNSW_PQ`

[This](https://github.com/lancedb/lance/pull/2552) can fix this but it requires to re-create the index

**Comment by wjones127** [comment]
> I executed the command to create an index (IVF_PQ) on a 40 million dataset, which took 624.80 seconds. After that, I added a piece of data and executed the optimize command(it works), which took 612.59 seconds. What is the difference between the two methods in adding new data to an existing index? I want to add new data to the index in the shortest possible time, but neither of these methods can do it.

Right now `optimize` defaults to re-writing an entire index when optimizing it. That's part of why it takes about the same amount of time to add new data to an index as it does to create the initial index.

In Lance, there is an undocumented parameter in `optimize_indices` (we should fix that) called `num_indices_to_merge`, which controls how the index rewrite happens. By default, this is 1, which means whenever it is called it will merge newly indexed data into one of the existing index segments. But you can also pass 0, which means it will just create a separate index fragment for new data, bypassing the need to rewrite the entire index. We might expose that in LanceDB soon, which might be useful for you here.

**Comment by wpjgit** [comment]
>But you can also pass 0, which means it will just create a separate index fragment for new data
Is this separate index fragment a new file?

I think I need to rephrase my needs.
Step 1: Create an empty table with one vector column and several scalar columns
Step 2: Create a vector index, because the final data of this table will be large
Step 3: Create a BTree index
Step 4: Add, update, or delete data.

I hope that the changed data in step 4 can be reflected in the vector and Btree index.

Should I call optimize_indices(num_indices_to_merge=0) immediately after adding, changing, or deleting a piece of data, or after changing many pieces of data? If you have a better way, please let me know.

When I use Milvue and es, I don't need to explicitly call a method like optimize in order to add the changed data to the index. Should we do the same in lance?

**Comment by wjones127** [comment]
> Is this separate index fragment a new file? Does this generate a lot of small files over time?

Yes and yes. Similar to data files, it might make sense to add a new file each time, but occasionally compact the index.

> Should I call optimize_indices(num_indices_to_merge=0) immediately after adding, changing, or deleting a piece of data, or after changing many pieces of data? If you have a better way, please let me know.

I would call `optimize_indices(num_indices_to_merge=0)` after changing / adding up to 1000 rows. Then every 10 times you call that, I would call `optimize_indices(num_indices_to_merge=20)` to compact the index segments together.

> When I use Milvue and es, I don't need to explicitly call a method like optimize in order to add the changed data to the index. Should we do the same in lance?

I think we would like to be able to do this. We have not yet designed how that mechanism should work.

**Comment by hdoer** [comment]
version: 0.17.0
language: typescript

Optimize is too expensive. I just want to make the new index text to be searched. I tried recreate the fts index, but it is too expensive too. Will a refresh function be provided in the future? Like elasticsearch.

**Comment by BubbleCal** [comment]
> version: 0.17.0 language: typescript
> 
> Optimize is too expensive. I just want to make the new index text to be searched. I tried recreate the fts index, but it is too expensive too. Will a refresh function be provided in the future? Like elasticsearch.

hi @hdoer, `optimize` should be faster than recreate, but yes it may be slow as well. There are some tips to improve this:
- pass `with_position=False` if you don't need phrase query feature
- pass `remove_stop_words=True`

both of them would significantly improve the indexing speed

for further steps, I'll work on improving the indexing perf, track [there](https://github.com/lancedb/lance/issues/3594)

**Comment by hpvd** [comment]
incremental indexing for FTS is solved:
https://github.com/lance-format/lance/issues/3594

incremental indexing for vector is solved
https://github.com/lance-format/lance/pull/4837

there are other open/related issues in the field of incremental index updates:
https://github.com/lancedb/lancedb/issues?q=is%3Aissue%20state%3Aopen%20incremental
