### ISSUE TITLE
bug(node): range end index 409300136 out of range for slice of length 624

### ISSUE THREAD

**Issue by ahaapple** [lancedb/lancedb#1525]
### LanceDB version

0.8.0 @lancedb/lancedb

### What happened?

```
thread 'tokio-runtime-worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.15.0/src/dataset.rs:355:43:
range end index 409300136 out of range for slice of length 501
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

range end index 409300136 out of range for slice of length 565

thread 'tokio-runtime-worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.15.0/src/dataset.rs:355:43:
range end index 409300136 out of range for slice of length 624
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: Panic in async function
 code: "GenericFailure"


thread 'tokio-runtime-worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.15.0/src/dataset.rs:355:43:
range end index 409300136 out of range for slice of length 624
error: Panic in async function
 code: "GenericFailure"
```

### Are there known steps to reproduce?

https://github.com/memfreeme/vector-test/ 

Here are the simplest steps to reproduce.

https://github.com/memfreeme/vector-test/tree/main/broken-data  Is the data directory corrupted

**Comment by wjones127** [comment]
Hi @ahaapple what operation gave you that failure? I have downloaded that table and I am both able to scan it and make a vector query successfully. Could you share the line that caused you to get the error message?

**Comment by ahaapple** [comment]
```
bun test test/index-jsonl.test.ts
```
insert or compaction.

These lines of code:
```
export async function ingest_jsonl(url: string, userId: string) {
  const data = await readFromJsonlFile(url);
  const table = await append(userId, data);
  if (Math.random() < 1 / 10) {
    await table.optimize({ cleanupOlderThan: new Date() });
    console.log(`${userId} table optimized`);
  } else {
    console.log(`${userId} table not optimized this time`);
  }
}

```

Yes, the strange thing is that the query does not fail. But in my test today, this error was reported dozens of times, and it did not report an error when testing based on local files, but it did report this error when testing based on S3.

**Comment by wjones127** [comment]
Hi @ahaapple.

We think the error message you are seeing looks like a bug you would hit if you originally created the table with LanceDB 0.5.2, and then wrote to the same with a newer version. There was a bug in LanceDB 0.5.2 that would write tables that could not be read by later versions. 

This is because of a combination of two things:
 1. A bug was introduced in 0.5.2 in #1352 that made the experimental new file format the default
 2. In version 0.6.0 there was a breaking change in the experimental format, which made V2 files from earlier versions unreadable (upstream PR: https://github.com/lancedb/lance/pull/2426)

Could you double check the versions of LanceDB you were reading and writing these table with? If this aligns with the story I've outlined above, the solution is likely we need to migrate all your tables forward.

**Comment by ahaapple** [comment]
I think the version should be 0.8.0,  After I upgraded to version 0.8.0, I have been using version 0.8.0.

1 On the day of the failure, all my tables were rebuilt using the 0.8.0 version of the SDK

```
export async function reCreateEmptyTable(tableName: string) {
const db = await getConnection();
return await db.createEmptyTable(tableName, schema, { mode: "overwrite" });
}

```

2. When I reproduced the issue for you, I also only used version 0.8.0.

**Comment by InSuperposition** [comment]
## Context: Bun/Node + Arrow IPC ingestion mismatch

We’ve confirmed this issue is triggered by a JS↔Rust boundary mismatch in the ingestion pipeline, specifically around `sanitizeData` and Arrow object identity checks.

### Observed behavior
- `table.add()` passes through `sanitizeData` in the JS layer
- In Bun/Node (ESM/CJS mixed environments), `instanceof Arrow classes` breaks across realms
- This causes `sanitizeData` to reconstruct **0-row RecordBatches**
- Rust backend then receives a structurally valid but empty payload → leading to panic or silent ingestion failure

### Workaround used in production
We bypass the JS sanitization layer entirely:

- Serialize `RecordBatch` → Arrow IPC stream (`Buffer`)
- Call `table.inner.add(buf, "append")`

This routes data directly into the Rust ingestion layer and avoids the JS sanitization path that is currently unstable in Bun/Node environments.

### Implication
This suggests `sanitizeData` is acting as a second schema enforcement layer that is not portable across JS runtimes, especially where class identity is not preserved.

### Related issue
This also exposes schema handling inconsistencies that become more visible when schema evolution is involved (see #3136).
