### ISSUE TITLE
bug(python): to_polars().colect() not working with latest polars version

### ISSUE THREAD

**Issue by laxas** [lancedb/lancedb#1539]
### What happened?

db = lancedb.connect("my_db")
df = db.open_table("my_table").to_polars().collect()

With polars version 1.4.1 installed, this returns the following error:

`polars.exceptions.ComputeError: TypeError: _scan_pyarrow_dataset_impl() got multiple values for argument 'batch_size'`

.to_polars is ok but the .collect() returns the error  

No problems with polars version 1.3.0.

### Are there known steps to reproduce?

1. Install polars 1.4.1 and python lancedb 0.3.2.
2. try to load a table with db.open_table("my_table").to_polars().collect()

**Comment by sayandipdutta** [comment]
`polars` repo says this about the underlying function [1](https://github.com/pola-rs/polars/blob/b2550a092e34aa40f8786f45ff67cab96c93695d/py-polars/polars/io/pyarrow_dataset/functions.py#L13-L25):
```python
@unstable()
def scan_pyarrow_dataset(
    source: pa.dataset.Dataset,
    *,
    allow_pyarrow_filter: bool = True,
    batch_size: int | None = None,
) -> LazyFrame:
    """
    Scan a pyarrow dataset.

    .. warning::
        This functionality is considered **unstable**. It may be changed
        at any point without it being considered a breaking change.

    ...

    """
```

So I guess it *did get changed*. A workaround to consider would be: `polars.from_arrow(db.open_table("my_table").to_arrow())`

**Comment by laxas** [comment]
Is there a plan to fix the broken polars integration in future lancedb versions?

**Comment by laxas** [comment]
I checked again with the latest version of polars. This is my test script:

```python
import polars as pl
import lancedb

db = lancedb.connect("/tmp/lancedb_test_db")

if "greatings" not in db.table_names():
    _df = pl.DataFrame(["hi", "hello"], schema={"greating": pl.Utf8})
    db.create_table("greatings", _df)
table = db.open_table("greatings")
df = table.to_polars().collect()
print(df)
```

With lancedb v0.15.0 and polars v1.12.0 I still get the following error:

```
Traceback (most recent call last):
  File "/tmp/lance_polars/lance_polars.py", line 10, in <module>
    df = table.to_polars().collect()
  File "/tmp/lance_polars/.venv/lib/python3.13/site-packages/polars/lazyframe/frame.py", line 2055, in collect
    return wrap_df(ldf.collect(callback))
                   ~~~~~~~~~~~^^^^^^^^^^
polars.exceptions.ComputeError: TypeError: _scan_pyarrow_dataset_impl() got multiple values for argument 'batch_size'
```
The workeround https://github.com/lancedb/lancedb/issues/1539#issuecomment-2316089589 does not return a lazy frame. That makes filtering more complicated.

Is there anyone that can help?

**Comment by eddyxu** [comment]
I will look into this today.

**Comment by eddyxu** [comment]
Talked with @westonpace , this requires a upstream fix in datafusion. We are tracking the work in https://github.com/lancedb/lance/issues/3133.

**Comment by pavanramkumar** [comment]
Can confirm reproducing this error. 

```
TypeError: _scan_pyarrow_dataset_impl() got multiple values for argument 'batch_size'
```

`lf.collect()` is working as expected for polars 1.3.0 but not recent versions. 

works for these versions:
```
>>> import pyarrow
>>> pyarrow.__version__
'20.0.0'
>>> import lancedb
>>> lancedb.__version__
'0.24.0'
>>> import polars
>>> polars.__version__
'1.3.0'
```

Is there an active fix being worked on? I see that this issue has been open for a while too:
https://github.com/lancedb/lance/issues/3133

**Comment by lcorcodilos** [comment]
Still seeing this in LanceDB 0.25.2 and Polars 1.35.1 and commenting to bump. Thanks!

**Comment by prrao87** [comment]
Just wanted to add this simple example that doesn't work, either (polars 1.35.1, lancedb 0.25.2):

```py
import lancedb
import polars as pl

uri = "./data/sample-lancedb"
db = lancedb.connect(uri)

data = pl.DataFrame(
    {
        "vector": [[3.1, 4.1], [5.9, 26.5]],
        "item": ["foo", "bar"],
        "price": [10.0, 20.0],
    }
)

tbl = db.create_table("items", data, mode="overwrite")

print(tbl.to_polars())
```
Returns:
```
naive plan: (run LazyFrame.explain(optimized=True) to see the optimized plan)

PYTHON SCAN []
PROJECT */3 COLUMNS
```
Trying to collect the first element of the LazyFrame also doesn't work with the same user-reported error above:
```py
print(tbl.to_polars().first().collect())
```
```
TypeError: _scan_pyarrow_dataset_impl() got multiple values for argument 'batch_size'
```

**Comment by westonpace** [comment]
Hmm, looks like we use https://docs.pola.rs/api/python/dev/reference/api/polars.scan_pyarrow_dataset.html on this path.  That method is marked unstable and can change anytime.  And it looks like this method is just broken.  I can reproduce without using lance at all:

```
import polars as pl
import pyarrow as pa
import pyarrow.dataset as ds

data = pa.table({
    "vector": [[3.1, 4.1], [5.9, 26.5]],
    "item": ["foo", "bar"],
    "price": [10.0, 20.0],
})
pyds = ds.dataset(data)
print(pl.scan_pyarrow_dataset(pyds, allow_pyarrow_filter=False).first().collect())
```

Curiously, it doesn't happen if I set `allow_pyarrow_filter=True`.

I wonder if it's time to just add a `scan_lance` to polars?  There is already a `scan_iceberg` and `scan_delta`.

**Comment by westonpace** [comment]
I've opened https://github.com/pola-rs/polars/issues/25316

**Comment by prrao87** [comment]
Would love this, wondering how we can get this going?
> I wonder if it's time to just add a `scan_lance` to polars? There is already a `scan_iceberg` and `scan_delta`.

Community support would help!

**Comment by alexander-beedie** [comment]
> So I guess it _did get changed_. A workaround to consider would be: `polars.from_arrow(db.open_table("my_table").to_arrow())`

> And it looks like this method is just broken. I can reproduce without using lance at all

FYI: the _"got multiple values for argument 'batch_size'"_ error is a bug that came about following a Rust-side refactor rather than any kind of intentional change on our side; I've just fixed it in https://github.com/pola-rs/polars/pull/25654, which will make it into the imminent  1.36.0 release 😅

**Comment by alexander-beedie** [comment]
FYI: we released Polars 1.36.0 (followed by a quick 1.36.1 hotfix)  last week, including the fix mentioned above, so you should be able to close this issue. (Test coverage was added so the same error won't recur in the future 👍)

**Comment by prrao87** [comment]
Thanks @alexander-beedie. I just confirmed that this fix works on Polars 1.36.1 and LanceDB 0.26.0.
