### ISSUE TITLE
bug(node): TypeError: lancedb.Index.fts is not a function

### ISSUE THREAD

**Issue by gy9527** [lancedb/lancedb#1557]
### LanceDB version

0.9.0

### What happened?

I am trying to implement full-text search using JavaScript, but I encountered an error when testing the official sample code.

### Are there known steps to reproduce?

`import * as lancedb from "@lancedb/lancedb";
const uri = "data/sample-lancedb"
const db = await lancedb.connect(uri);

const data = [
{ vector: [3.1, 4.1], text: "Frodo was a happy puppy" },
{ vector: [5.9, 26.5], text: "There are several kittens playing" },
];
const tbl = await db.createTable("my_table", data, { mode: "overwrite" });
await tbl.createIndex("text", {
    config: lancedb.Index.fts(),
});

await tbl
    .search("puppy")
    .select(["text"])
    .limit(10)
    .toArray();`

**Comment by gy9527** [comment]
I upgraded to version 0.10.0-beta.0, but it reported a new bug.

Error: No embedding functions are defined in the table

**Comment by BubbleCal** [comment]
Hi @gy9527 , I think something breaks this,
#1576 would fix this, but you can still do FTS by this for now:
```
await tbl
  .search("puppy", "fts")
  .select(["text"])
  .limit(10)
  .toArray();`
```

**Comment by phpmac** [comment]
```
[2024-10-31T16:13:37Z TRACE lance_encoding::encodings::logical::primitive] Final flush of column 0 which has 680 bytes
[2024-10-31T16:13:37Z TRACE lance_encoding::encodings::logical::primitive] Final flush of column 1 which has 376 bytes
table NativeTable(messages, uri=/Users/a/Downloads/hardhat/lancedb/messages.lance, read_consistency_interval=None)
Error: No embedding functions are defined in the table
    at /Users/a/Downloads/hardhat/node_modules/@lancedb/lancedb/dist/table.js:186:39
    at async /Users/a/Downloads/hardhat/node_modules/@lancedb/lancedb/dist/query.js:451:31
    at async VectorQuery.toArrow (/Users/a/Downloads/hardhat/node_modules/@lancedb/lancedb/dist/query.js:215:21)
    at async VectorQuery.toArray (/Users/a/Downloads/hardhat/node_modules/@lancedb/lancedb/dist/query.js:228:21)
    at async aiDb (/Users/a/Downloads/hardhat/scripts/tmp.ts:61:19)
    at async main (/Users/a/Downloads/hardhat/scripts/tmp.ts:7:3)
    ```
    
    
    
    
    ```
    
  // 创建表
  const table = await db.createTable(
    "messages",
    [
      { text: "消息内容1", createdAt: new Date() },
      { text: "消息内容2", createdAt: new Date() },
      { text: "测试", createdAt: new Date() },
    ],
    {
      mode: "overwrite",
    }
  );
  console.debug(`table`, table);


  // 搜索消息
  const results = await table.search("测试").toArray();
  console.debug(`results`, results);

```
when search

**Comment by BubbleCal** [comment]
> await tbl
>   .search("puppy", "fts")
>   .select(["text"])
>   .limit(10)
>   .toArray();`

passing the `queryType` to fix it:
```
await tbl
  .search("puppy", "fts")
  .select(["text"])
  .limit(10)
  .toArray();`
```

btw i don't think we support Chinese for now, that may result in unexpected search results

**Comment by phpmac** [comment]
> > await tbl
> 
> >   .search("puppy", "fts")
> 
> >   .select(["text"])
> 
> >   .limit(10)
> 
> >   .toArray();`
> 
> 
> 
> passing the `queryType` to fix it:
> 
> ```
> 
> await tbl
> 
>   .search("puppy", "fts")
> 
>   .select(["text"])
> 
>   .limit(10)
> 
>   .toArray();`
> 
> ```
> 
> 
> 
> btw i don't think we support Chinese for now, that may result in unexpected search results

The same goes for English.

**Comment by BubbleCal** [comment]
> > > await tbl
> > 
> > >   .search("puppy", "fts")
> > 
> > >   .select(["text"])
> > 
> > >   .limit(10)
> > 
> > >   .toArray();`
> > 
> > 
> > 
> > passing the `queryType` to fix it:
> > 
> > ```
> > 
> > await tbl
> > 
> >   .search("puppy", "fts")
> > 
> >   .select(["text"])
> > 
> >   .limit(10)
> > 
> >   .toArray();`
> > 
> > ```
> > 
> > 
> > 
> > btw i don't think we support Chinese for now, that may result in unexpected search results
> 
> The same goes for English.

Does it still report error with passing query_type?
