### ISSUE TITLE
bug(python): AttributeError: 'generator' object has no attribute 'to_batches'

### ISSUE THREAD

**Issue by mneedham** [lancedb/lancedb#1606]
### LanceDB version

v0.12.0

### What happened?

I'm trying out the examples on these two pages:

https://lancedb.github.io/lancedb/embeddings/available_embedding_models/multimodal_embedding_functions/openclip_embedding/
https://lancedb.github.io/lancedb/notebooks/DisappearingEmbeddingFunction/

And I run into this error when I run the `table.add` line:

```text
OSError                                   Traceback (most recent call last)
Cell In[63], line 27
     25 # get each uri as bytes
     26 image_bytes = [requests.get(uri).content for uri in uris]
---> 27 table.add(
     28     pd.DataFrame({"label": labels, "image_uri": uris, "image_bytes": image_bytes})
     29 )

File ~/projects/learndatawithmark/lance-multi-modal/.venv/lib/python3.12/site-packages/lancedb/table.py:1308, in LanceTable.add(self, data, mode, on_bad_vectors, fill_value)
   1306 # Access the dataset_mut property to ensure that the dataset is mutable.
   1307 self._ref.dataset_mut
-> 1308 self._ref.dataset = lance.write_dataset(
   1309     data, self._dataset_uri, schema=self.schema, mode=mode
   1310 )

File ~/projects/learndatawithmark/lance-multi-modal/.venv/lib/python3.12/site-packages/lance/dataset.py:2740, in write_dataset(data_obj, uri, schema, mode, max_rows_per_file, max_rows_per_group, max_bytes_per_file, commit_lock, progress, storage_options, data_storage_version, use_legacy_format)
   2737     params["commit_handler"] = commit_lock
   2739 uri = os.fspath(uri) if isinstance(uri, Path) else uri
-> 2740 inner_ds = _write_dataset(reader, uri, params)
   2742 ds = LanceDataset.__new__(LanceDataset)
   2743 ds._ds = inner_ds

OSError: LanceError(Arrow): C Data interface error: Unknown error: 'generator' object has no attribute 'to_batches'. Detail: Python exception: Traceback (most recent call last):
  File "/Users/markhneedham/projects/learndatawithmark/lance-multi-modal/.venv/lib/python3.12/site-packages/lance/dataset.py", line 2863, in _casting_recordbatch_iter
    for batch in input_iter:
  File "/Users/markhneedham/projects/learndatawithmark/lance-multi-modal/.venv/lib/python3.12/site-packages/lancedb/table.py", line 210, in _to_record_batch_generator
    for b in batch.to_batches():
             ^^^^^^^^^^^^^^^^
AttributeError: 'generator' object has no attribute 'to_batches'
, /Users/runner/work/lance/lance/rust/lance-datafusion/src/utils.rs:41:28

```

### Are there known steps to reproduce?

Follow the guide is all I did. I'm using a Mac M1 in case that's useful to know.

**Comment by AyushExel** [comment]
Could it be something related to OSError? I see that in your error trace but its probably cut out. Can you paste the full log?
I just tried the example in the first link on a fresh colab and it worked. 
<img width="1187" alt="Screenshot 2024-09-06 at 11 21 56 AM" src="https://github.com/user-attachments/assets/916dc15b-5b62-4926-841e-8bdb4fefd13b">

**Comment by mneedham** [comment]
That was the full log! But I killed my iPython session and did everything from scratch and now it works just like for you.

```
$ python app.py
/Users/markhneedham/projects/learndatawithmark/lance-multi-modal/.venv/lib/python3.12/site-packages/open_clip/factory.py:129: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path, map_location=map_location)
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 34.08it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 34.04it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 35.50it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 37.55it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 35.93it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 35.82it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 38.70it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 34.93it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 34.53it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 34.20it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:02<00:00, 30.33it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 35.64it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 35.15it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:01<00:00, 34.58it/s]
100%|███████████████████████████████████████████████████| 64/64 [00:02<00:00, 27.52it/s]
100%|███████████████████████████████████████████████████| 40/40 [00:01<00:00, 34.02it/s]
```

I'm not really sure what I did wrong the first time, but thanks for taking a look. Seems to be working now.
