### ISSUE TITLE
bug(python): ValueError: Syntax Error for some special query text when reranking

### ISSUE THREAD

**Issue by ousiax** [lancedb/lancedb#1617]
### LanceDB version

v0.12.0

### What happened?

When using reranking, `ValueError: Syntax Error` occured for  some special query text like `Calibration file write failed, Message: {0}, StackTrace: {1}`.

Because I'm not good at Rust, I can't debug it by myself.

### Are there known steps to reproduce?

```py
import os
import lancedb
import torch
from lancedb.embeddings import get_registry
from lancedb.pydantic import LanceModel, Vector
from lancedb.rerankers import LinearCombinationReranker


os.environ['HF_HUB_OFFLINE'] = '1'
os.environ['HF_DATASETS_OFFLINE'] = '1'
os.environ['HF_ENDPOINT'] = 'https://hf-mirror.com'

db = lancedb.connect('./.lancedb')
device = "cuda" if torch.cuda.is_available() else "cpu"
st = get_registry().get('sentence-transformers')
model = st.create(name="BAAI/bge-small-zh-v1.5", device=device)


class Words(LanceModel):
    module: str | None
    tag: str | None
    text: str = model.SourceField()
    vector: Vector(model.ndims()) = model.VectorField()  # type: ignore


table = db.create_table("words", schema=Words, mode="create", exist_ok=True)
table.add(
    [
        {'module': None, "text": "hello world", "tag": 'foo'},
        {"tag": "bar", "text": "goodbye 世界"},
    ]
)

query = "Calibration file write failed, Message: {0}, StackTrace: {1}"
reranker = LinearCombinationReranker()

# Run hybrid search with a reranker
table.create_fts_index("text", replace=True)
result = (
    table.search(query=query, query_type="hybrid")
    .rerank(reranker=reranker)
    .to_list()
)

for rst in result:
    print(rst)
```

```console
$ python demo.py
....
Traceback (most recent call last):
  File "C:\Users\<username>\learn\py\lancedb-samples\demo.py", line 42, in <module>
    .to_list()
     ^^^^^^^^^
  File "C:\Users\<username>\.virtualenvs\lancedb-samples-ts7VLQLo\Lib\site-packages\lancedb\query.py", line 303, in to_list
    return self.to_arrow().to_pylist()
           ^^^^^^^^^^^^^^^
  File "C:\Users\<username>\.virtualenvs\lancedb-samples-ts7VLQLo\Lib\site-packages\lancedb\query.py", line 853, in to_arrow
    fts_results = fts_future.result()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<username>\.virtualenvs\lancedb-samples-ts7VLQLo\Lib\site-packages\lancedb\query.py", line 725, in to_arrow
    row_ids, scores = search_index(
                      ^^^^^^^^^^^^^
  File "C:\Users\<username>\.virtualenvs\lancedb-samples-ts7VLQLo\Lib\site-packages\lancedb\fts.py", line 195, in search_index
    query = index.parse_query(query)
            ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Syntax Error: Calibration file write failed, Message: {0}, StackTrace: {1}
```

**Comment by wjones127** [comment]
I believe this error comes from tantivy. I'd guess it's having trouble parsing the `{` and `}` characters.

**Comment by QianZhu** [comment]
@ousiax If you use LanceDB's native FTS, the issue, as Will brought it up above,  would be resolved. `table.create_fts_index("text", replace=True, use_tantivy=False)`

**Comment by dantetemplar** [comment]
> [@ousiax](https://github.com/ousiax) If you use LanceDB's native FTS, the issue, as Will brought it up above, would be resolved. `table.create_fts_index("text", replace=True, use_tantivy=False)`

Why is this counted as a solution? This is not a fix for the problem, but simply avoiding it. It seems that escaping of all special characters is required here when working with tantivy: https://quickwit.io/docs/reference/query-language#escaping-special-characters
