### ISSUE TITLE
Contextualizer doesn't validate the arguments

### ISSUE THREAD

**Issue by wjones127** [lancedb/lancedb#164]
If you don't know you need to pass `window` `stride` and `groupby`, you can get confusing error messages. For example

```python
from lancedb.context import contextualize
import pandas as pd
data = pd.DataFrame({
   'token': ['The', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog', 'I', 'ate', 'a', 'sandwich'],
   'document_id': [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2]
})
contextualize(data).window(3).to_df()
```

```
Traceback (most recent call last):
  File "/Users/willjones/mambaforge/envs/lance-dev/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/willjones/Documents/lancedb/python/lancedb/context.py", line 145, in to_df
    return process_group(self._raw_df)
  File "/Users/willjones/Documents/lancedb/python/lancedb/context.py", line 136, in process_group
    text = grp[self._text_col].values
  File "/Users/willjones/mambaforge/envs/lance-dev/lib/python3.10/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/willjones/mambaforge/envs/lance-dev/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: None
```

**Comment by trueutkarsh** [comment]
Hi Will,
I would like to pick this issue. As I understand there is no valid arguement checking in text_col, window and stride methods for Contextualizer class. Even for group_by there is no check if the input string is a column's name. 

Also in the to_df() method for Contextualizer there should be checks if text_col, window and stride are not None else it should raise an invalid input error. 

Finally there are no integration tests written as well for the Contextualizer class or contextualizer method which should be added.

Please let me know your thoughts over this and correct my understanding if wrong anywhere and possibly give a green light and I can start working on it.

Thanks

**Comment by wjones127** [comment]
Hi @trueutkarsh. Your understanding is correct. However, someone has already started working on this in #168. Feel free to leave comments in there if you have suggestions.
