### ISSUE TITLE
bug(python): ValueError: Expected x dimensions but got y for str

### ISSUE THREAD

**Issue by jagadeshanh** [lancedb/lancedb#1705]
### LanceDB version

0.13.0

### What happened?

I am trying to insert a text and a vector in to lancedb table, but I get this ValueError

lancedb version: **lancedb-0.13.0**

```
# !pip install lancedb

from lancedb.pydantic import Vector, LanceModel
import lancedb
import pandas as pd

class PostSchema(LanceModel):
    post_id: str
    post_text: str
    vector: Vector(4)

db = lancedb.connect("./lancedb")
db.create_table('posts', schema=PostSchema)

posts = [{
    'post_id': '1',
    'post_text': 'Hello World',
    'embedding': [1,2,3,4]
}]

df = pd.DataFrame(posts)
posts_table = db.open_table('posts')

for index, row in df.iterrows():
    posts_table.add({
        'post_id': row['post_id'],
        'post_text': row['post_text'],
        'vector': row['embedding']
    })
```

Full error:

```
ValueError                                Traceback (most recent call last)
[<ipython-input-9-4e89ee9085ac>](https://localhost:8080/#) in <cell line: 12>()
     11 
     12 for index, row in df.iterrows():
---> 13     posts_table.add({
     14         'post_id': row['post_id'],
     15         'post_text': row['post_text'],

3 frames
[/usr/local/lib/python3.10/dist-packages/lance/vector.py](https://localhost:8080/#) in _validate_ndim(values, ndim)
     37         else:
     38             if ndim != len(v):
---> 39                 raise ValueError(f"Expected {ndim} dimensions but got {len(v)} for {v}")
     40     return ndim
     41 

ValueError: Expected 1 dimensions but got 11 for Hello World
```

### Are there known steps to reproduce?

Create a fresh notebook

Install lancedb

copy paste the code in a cell and execute

**Comment by jagadeshanh** [comment]
https://colab.research.google.com/drive/1YyeeBNZEO0b_2AQiBsEzNJNPlNiG1Stk?usp=sharing

here is a notbook link

**Comment by wjones127** [comment]
Hi @jagadeshanh . `add()` expects more than one row at a time. So it interprets a dictionary as a set of columns, not as a single row. To correctly add a single row, wrap it in a Python list:
```python
for index, row in df.iterrows():
    posts_table.add([{
        'post_id': row['post_id'],
        'post_text': row['post_text'],
        'vector': row['embedding']
    }])
```

**Comment by wjones127** [comment]
Though I am noticing what I would expect to work for dictionary doesn't

```python
>>> data = {
...     'post_id': [1, 2, 3],
...     'post_text': ["hello", "world", "goodbye"],
...     'vector': [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]
... }
>>> posts_table.add(data)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/willjones/mambaforge/envs/notebooks/lib/python3.10/site-packages/lancedb/table.py", line 1400, in add
    data, _ = _sanitize_data(
  File "/Users/willjones/mambaforge/envs/notebooks/lib/python3.10/site-packages/lancedb/table.py", line 102, in _sanitize_data
    data = vec_to_table(data)
  File "/Users/willjones/mambaforge/envs/notebooks/lib/python3.10/site-packages/lance/vector.py", line 103, in vec_to_table
    vectors = _normalize_vectors(values, ndim)
  File "/Users/willjones/mambaforge/envs/notebooks/lib/python3.10/site-packages/lance/vector.py", line 29, in _normalize_vectors
    values = np.array(vectors, dtype="float32").ravel()
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 3) + inhomogeneous part.
```

**Comment by jagadeshanh** [comment]
Thanks @wjones127 for the response, yes the passing array to add function worked.
