### ISSUE TITLE
bug(python): Error trying to create Colbert reranker

### ISSUE THREAD

**Issue by tleyden** [lancedb/lancedb#1756]
### LanceDB version

0.14.0

### What happened?

I used a code sample in [these docs](https://blog.lancedb.com/hybrid-search-and-reranking-report/), but get an error:

```
ImportError: Please install rerankers
``` 

Details below.

### Are there known steps to reproduce?

I tried this on a fresh conda env

```
conda create -n lancedb_reranker python=3.11.5
conda activate lancedb_reranker
```

in py shell:

```
Python 3.11.5 (main, Sep 11 2023, 08:31:25) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from lancedb.rerankers import ColbertReranker
>>> colbert = ColbertReranker()
Traceback (most recent call last):
  File "/Users/tleyden/miniconda3/envs/lancedb_reranker/lib/python3.11/site-packages/lancedb/util.py", line 154, in attempt_import_or_raise
    return importlib.import_module(module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tleyden/miniconda3/envs/lancedb_reranker/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rerankers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tleyden/miniconda3/envs/lancedb_reranker/lib/python3.11/site-packages/lancedb/rerankers/colbert.py", line 41, in __init__
    super().__init__(
  File "/Users/tleyden/miniconda3/envs/lancedb_reranker/lib/python3.11/site-packages/lancedb/rerankers/answerdotai.py", line 50, in __init__
    rerankers = attempt_import_or_raise(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tleyden/miniconda3/envs/lancedb_reranker/lib/python3.11/site-packages/lancedb/util.py", line 156, in attempt_import_or_raise
    raise ImportError(f"Please install {mitigation or module}")
ImportError: Please install rerankers
>>>
```

**Comment by janaka** [comment]
> Thanks for reporting.. The error asks you to install `rerankers`. It can be installed by `pip install rerankers`. We'll update the docs to better point out extra/optional dependencies for each reranker.

thanks - would be good to have the error message also emit run "pip install reranker"
