### ISSUE TITLE
bug(python): Vector Index creation fails with CUDA device

### ISSUE THREAD

**Issue by BTheunissen** [lancedb/lancedb#1766]
### LanceDB version

0.14.0

### What happened?

Getting a centroid shape error specifically when building vector index with `device='cuda'` since upgrading, confirmed that this same call works well on CPU with `device=None`.

Error Logs:
```
2024-10-22 19:19:17,868 [INFO] (3052) vector_store_table - Building index with partitions: 38 and sub vectors: 769, from 769 vectors with dimension 769, and metric dot
2024-10-22 19:19:17,868 [INFO] (3052) vector_store_table - Creating index with device: cuda
2024-10-22 19:19:17,868 [INFO] (3052) root - Randomly select 38 centroids from <lance.dataset.LanceDataset object at 0x7fa862a66030> (filt=vector is not null)
2024-10-22 19:19:17,907 [INFO] (3052) root - Done sampling: centroids shape: torch.Size([40, 769])
2024-10-22 19:19:17,908 [INFO] (3052) root - Training IVF partitions using GPU(cuda)
2024-10-22 19:19:17,908 [INFO] (3052) root - Start kmean training, metric: dot, iters: 50
2024-10-22 19:19:20,121 [INFO] (3052) root - Finish KMean training in 2.2132339477539062
2024-10-22 19:19:20,122 [INFO] (3052) root - Saved centroids to /tmp/tmpa_xeilpo
100%|██████████| 155975/155975 [00:01<00:00, 135535.00it/s]9318:
2024-10-22 19:19:21,274 [INFO] (3052) root - Saved precomputed partitions to /tmp/tmpziw4_wr2
2024-10-22 19:19:21,274 [ERROR] (3052) vector_store.vector_store_table - Failed to create index. Continuing without index...
Traceback (most recent call last):
  File "/vector_store/vector_store_table.py", line 566, in _make_vector_index
    self._table.create_index(
  File "/.venv/lib/python3.11/site-packages/lancedb/table.py", line 1316, in create_index
    self._dataset_mut.create_index(
  File "/.venv/lib/python3.11/site-packages/lance/dataset.py", line 1708, in create_index
    raise ValueError(

> ValueError: Ivf centroids must be 2D array: (clusters, dim), got (40, 769)
```

Machine Details:
```
Considered resources (1 node):
----------------------------------------------------------------------------------------------
 CLOUD   INSTANCE        vCPUs   Mem(GB)   ACCELERATORS   REGION/ZONE     COST ($)   CHOSEN
----------------------------------------------------------------------------------------------
 GCP     n1-highmem-16   16      104       T4:1           us-central1-a   1.30          ✔
----------------------------------------------------------------------------------------------
```

**Comment by westonpace** [comment]
It looks like the problem here is that we asked the dataset loader for 38 random vectors (to use as initial centroids) and we ended up with 40 due to https://github.com/lancedb/lance/pull/3066 .  Once that fix makes it into lancedb we can test this again and close if resolved.

**Comment by BTheunissen** [comment]
```
Traceback (most recent call last):
File "pyarrow/ipc.pxi", line 762, in pyarrow.lib.RecordBatchReader.read_all
File "/.venv/lib/python3.11/site-packages/lancedb/query.py", line 700, in to_arrow
^^^^^^^^^^
return self._pool_interactions_knn_retrieval(
File "/shaped-internal/src/shaped_internal/common/logging.py", line 200, in
return fn()
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
primitive array
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'lance_background_thread' panicked at /home/runner/work/lance/lance/rust/lance-core/src/utils/tokio.rs:65:24:
ValueError: Error when retrieving candidates.
```

Reusing this ticket, I recently reenabled Cuda device support on `v0.17.1` for building the vector index to speed-up index creation for dense text embedding tables, and I am seeing the above error when we attempt to query the table after the index is created with Cuda.

**Comment by ysdk2** [comment]
Any updates to this? Still getting this error in 0.29.2

**Comment by westonpace** [comment]
> Any updates to this? Still getting this error in 0.29.2

@ysdk2 

Can you run the query script with `RUST_BACKTRACE=1` and share what you get?

**Comment by samvallad33** [comment]
Python vector index creation failing with a CUDA device error blocks durable store bring-up on GPU hosts. Teams then cannot initialize recall even when CPU fallback should work. Are you detecting CUDA init failure and offering an explicit CPU index path with a clear error?
