### ISSUE TITLE
Feature: Support FTS indexes on nested fields

### ISSUE THREAD

**Issue by alexkreidler** [lancedb/lancedb#1787]
### SDK

Python

### Description

```python
import lancedb
import pyarrow.parquet as pq
# Connect to LanceDB
db = lancedb.connect("data/cases2.lance")

print(db.table_names())

data = pq.read_table("data/part-00000-bd7b5d85-e1bd-440b-8817-95ec234884f3-c000.gz.parquet")

# table = db.create_table("cases", data)
table = db.open_table("cases")
print(table)

# # Load the dataset
# Add a full-text search index on the 'opinion_text' field
table.create_fts_index(["opinions.opinion_text"], replace=True)
```
Data is from [this dataset](https://huggingface.co/datasets/harvard-lil/cold-cases?row=1#data-dictionary) (has data dictionary)

```
Traceback (most recent call last):
  File "/workspace/finch/rag/.pixi/envs/default/lib/python3.12/site-packages/lancedb/fts.py", line 107, in populate_index
    f = table.schema.field(name)  # raises KeyError if not found
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/types.pxi", line 2792, in pyarrow.lib.Schema.field
KeyError: 'Column opinions.opinion_text does not exist in schema'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/finch/rag/index.py", line 16, in <module>
    table.create_fts_index(["opinions.opinion_text"], replace=True)
  File "/workspace/finch/rag/.pixi/envs/default/lib/python3.12/site-packages/lancedb/table.py", line 1420, in create_fts_index
    populate_index(
  File "/workspace/finch/rag/.pixi/envs/default/lib/python3.12/site-packages/lancedb/fts.py", line 109, in populate_index
    f = resolve_path(table.schema, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/finch/rag/.pixi/envs/default/lib/python3.12/site-packages/lancedb/fts.py", line 169, in resolve_path
    raise KeyError(f"field {field_name} not found in schema {schema}")
KeyError: 'field opinions.opinion_text not found in schema id: int32\njudges: string\ndate_filed: date32[day]\ndate_filed_is_approximate: bool not null\nslug: string\ncase_name_short: string\ncase_name: string\ncase_name_full: string\nattorneys: string\nnature_of_suit: string\nposture: string\nsyllabus: string\nheadnotes: string\nsummary: string\ndisposition: string\nhistory: string\nother_dates: string\ncross_reference: string\ncorrection: string\ncitation_count: int32\nprecedential_status: string\narguments: string\nheadmatter: string\ncitations: list<element: string not null>\n  child 0, element: string not null\nopinions: list<element: struct<author_str: string, per_curiam: bool not null, type: string, page_count: int32, download_url: string, author_id: int32, opinion_text: string, ocr: bool not null, opinion_id: int32> not null>\n  child 0, element: struct<author_str: string, per_curiam: bool not null, type: string, page_count: int32, download_url: string, author_id: int32, opinion_text: string, ocr: bool not null, opinion_id: int32> not null\n      child 0, author_str: string\n      child 1, per_curiam: bool not null\n      child 2, type: string\n      child 3, page_count: int32\n      child 4, download_url: string\n      child 5, author_id: int32\n      child 6, opinion_text: string\n      child 7, ocr: bool not null\n      child 8, opinion_id: int32\ncourt_short_name: string\ncourt_full_name: string\ncourt_type: string\ncourt_jurisdiction: string\n-- schema metadata --\norg.apache.spark.version: \'3.4.0\'\norg.apache.spark.sql.parquet.row.metadata: \'{"type":"struct","fields":[{"\' + 2737'
```

**Comment by wjones127** [comment]
That's odd. We were supposed to have fixed this in https://github.com/lancedb/lancedb/pull/723, but it appears we may have had a regression. Also see discussion in https://github.com/lancedb/lance/issues/1739

We have a test here for this:

https://github.com/lancedb/lancedb/blob/9708d829a991cefcee0e8354187cbf5681ce0897/python/python/tests/test_fts.py#L380-L383

I wonder what is different? `use_tantivy` still defaults to true, so I don't think it's that:

https://github.com/lancedb/lancedb/blob/9708d829a991cefcee0e8354187cbf5681ce0897/python/python/lancedb/table.py#L502

**Comment by wjones127** [comment]
Oh, here is the field for `opinions`:

```
opinions: list<element: struct<author_str: string, per_curiam: bool not null, type: string, page_count: int32, download_url: string, author_id: int32, opinion_text: string, ocr: bool not null, opinion_id: int32> not null>
```

Opinions is a list, not a struct. We don't currently support list columns in FTS.
