### ISSUE TITLE
bug(node): @lancedb/lancedb does not support remote tables directly in the storage root

### ISSUE THREAD

**Issue by albertlockett** [lancedb/lancedb#1944]
### LanceDB version

0.14.0

### What happened?

When connecting to remote db using `vectordb` npm package, it used to be possible to pass `db://` to the uri to signify that we wanted to use a table that isn't nested under some additional database directory.
```js
const conn = await db.connect({
  uri: 'db://',
  // ...
```
This is no longer supported with the `@lancedb/lancedb` package. Instead we get this error:
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Invalid input, Invalid database URL (missing host) 'db://'] {
  code: 'GenericFailure'
}

Node.js v18.19.0
```

Wondering if we should support this for backward compatibility?

**Comment by albertlockett** [comment]
This is also something we might consider supporting in the python SDK, as it does not work:

```
db = lancedb.connect(
    uri="db://",
  # ...
)
```

result:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/albertlockett/Development/tmp_python/index.py", line 6, in <module>
    db = lancedb.connect(
        uri="db://",
    ...<2 lines>...
        host_override="http://localhost:10024"
    )
  File "/Users/albertlockett/Development/tmp_python/venv/lib/python3.13/site-packages/lancedb/__init__.py", line 105, in connect
    return RemoteDBConnection(
        uri,
    ...<6 lines>...
        **kwargs,
    )
  File "/Users/albertlockett/Development/tmp_python/venv/lib/python3.13/site-packages/lancedb/remote/db.py", line 90, in __init__
    self._conn = LOOP.run(
                 ~~~~~~~~^
        connect_async(
        ^^^^^^^^^^^^^^
    ...<5 lines>...
        )
        ^
    )
    ^
  File "/Users/albertlockett/Development/tmp_python/venv/lib/python3.13/site-packages/lancedb/background_loop.py", line 25, in run
    return asyncio.run_coroutine_threadsafe(future, self.loop).result()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/albertlockett/Development/tmp_python/venv/lib/python3.13/site-packages/lancedb/__init__.py", line 198, in connect_async
    await lancedb_connect(
    ...<7 lines>...
    )
ValueError: Invalid input, Invalid database URL (missing host) 'db://'
```

**Comment by Xuanwo** [comment]
Hi, this issue is a backward compatibility feature request regarding support for the `db://` URI scheme. The previous `vectordb` package supported this, but it is not a confirmed bug in the current `@lancedb/lancedb` package. We can discuss this as a feature request. I'm closing this now. Feel free to create a new issue if the problem still exists.
