### ISSUE TITLE
bug(python): got wrong type info from mypy for Vector

### ISSUE THREAD

**Issue by hongbo-miao** [lancedb/lancedb#1982]
### What happened?

Currently mypy gives error:

```sh
error: Invalid type comment or annotation  [valid-type]
note: Suggestion: use Vector[...] instead of Vector(...)
```

![image](https://github.com/user-attachments/assets/02800f0e-eb38-4737-8573-2d5276516055)

for line

```py
vector: Vector(EMEBEDDINGS.ndims()) = EMEBEDDINGS.VectorField()
```

mypy wants to change to

```py
vector: Vector[EMEBEDDINGS.ndims()] = EMEBEDDINGS.VectorField()
```

However, if change, then will get error during running:

```sh
Traceback (most recent call last):
  File "/Users/hongbo-miao/Clouds/Git/hongbomiao.com/machine-learning/hm-imagebind/src/main.py", line 34, in <module>
    class MultimodalSearchSchema(LanceModel):
  File "/Users/hongbo-miao/Clouds/Git/hongbomiao.com/machine-learning/hm-imagebind/src/main.py", line 38, in MultimodalSearchSchema
    vector: Vector[EMEBEDDINGS.ndims()] = EMEBEDDINGS.VectorField()
TypeError: 'function' object is not subscriptable
```

So I assume mypy is giving wrong info currently.

**Comment by BubbleCal** [comment]
currently `Vector` is a function that returns a type, so `Vector[dim]` can't work.
@eddyxu do you have more infos about this?

**Comment by eddyxu** [comment]
Lemme look into it.
