### ISSUE TITLE
open_table + create_table error implementation

### ISSUE THREAD

**Issue by unkn-wn** [lancedb/lancedb#216]
Both `open_table()` and `create_table()` don't provide any errors when opening and creating empty/non-existent databases. The errors should show on function call instead of on the `add()` function. Windows, Python 3.8.10

> create_table()
```py
>>> tbl = db.create_table("hi")

>>> test
[{'id': 100, 'vector': [10, 10], 'meta': 'data', 'meta2': 'data2'}, {'id': 101, 'vector': [11, 11], 'meta': 'ATAD', 'meta2': '2ATAD'}]

>>> tbl.add(test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leony/.local/lib/python3.8/site-packages/lancedb/table.py", line 256, in add
    data = _sanitize_data(data, self.schema)
  File "/home/leony/.local/lib/python3.8/site-packages/lancedb/table.py", line 107, in schema
    return self._dataset.schema
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/leony/.local/lib/python3.8/site-packages/lancedb/table.py", line 234, in _dataset
    return lance.dataset(self._dataset_uri, version=self._version)
  File "/home/leony/.local/lib/python3.8/site-packages/lance/__init__.py", line 56, in dataset
    ds = LanceDataset(uri, version, block_size)
  File "/home/leony/.local/lib/python3.8/site-packages/lance/dataset.py", line 48, in __init__
    self._ds = _Dataset(uri, version, block_size, index_cache_size)
ValueError: Dataset at path home/leony/.lancedb/hi.lance/_latest.manifest was not found: Not found: home/leony/.lancedb/hi.lance/_latest.manifest
```

> open_table()
```py
>>> tbl = db.open_table("nonexistent")
>>> tbl.add(test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leony/.local/lib/python3.8/site-packages/lancedb/table.py", line 256, in add
    data = _sanitize_data(data, self.schema)
  File "/home/leony/.local/lib/python3.8/site-packages/lancedb/table.py", line 107, in schema
    return self._dataset.schema
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/leony/.local/lib/python3.8/site-packages/lancedb/table.py", line 234, in _dataset
    return lance.dataset(self._dataset_uri, version=self._version)
  File "/home/leony/.local/lib/python3.8/site-packages/lance/__init__.py", line 56, in dataset
    ds = LanceDataset(uri, version, block_size)
  File "/home/leony/.local/lib/python3.8/site-packages/lance/dataset.py", line 48, in __init__
    self._ds = _Dataset(uri, version, block_size, index_cache_size)
ValueError: Dataset at path home/leony/.lancedb/nonexistent.lance/_latest.manifest was not found: Not found: home/leony/.lancedb/nonexistent.lance/_latest.manifest
'''

**Comment by jaichopra** [comment]
So we are not actually creating tables when the data field is empty (i.e. this is a larger bug) 
you can this by checking with `db.table_names()`

**Comment by unkn-wn** [comment]
Yeah, I noticed, so my plan currently is just to produce an error when trying to create with no data, and later we can fix the bigger problem
