### ISSUE TITLE
[python] Error messaging for inserting one element without using a list

### ISSUE THREAD

**Issue by TevinWang** [lancedb/lancedb#409]
`db.create_table("videos", {'vector': image_features.numpy()[0].tolist(), 'video_id': video_id, 'start_time': (int(frame) - 1) * 30})`

Inserting one element without enclosing in list results in this error:
```
Traceback (most recent call last):
  File "/Users/tevinwang/Documents/repos/tevinwang/vectordb-recipes/examples/multimodal_video_search/insert.py", line 33, in <module>
    insert(video_ids[0], frames[0])
  File "/Users/tevinwang/Documents/repos/tevinwang/vectordb-recipes/examples/multimodal_video_search/insert.py", line 25, in insert
    db.create_table("videos", {'vector': image_features.numpy()[0].tolist(), 'video_id': video_id, 'start_time': (int(frame) - 1) * 30})
  File "/Users/tevinwang/Documents/repos/tevinwang/vectordb-recipes/venv/lib/python3.10/site-packages/lancedb/db.py", line 294, in create_table
    tbl = LanceTable.create(
  File "/Users/tevinwang/Documents/repos/tevinwang/vectordb-recipes/venv/lib/python3.10/site-packages/lancedb/table.py", line 523, in create
    data = _sanitize_data(
  File "/Users/tevinwang/Documents/repos/tevinwang/vectordb-recipes/venv/lib/python3.10/site-packages/lancedb/table.py", line 47, in _sanitize_data
    data = vec_to_table(data)
  File "/Users/tevinwang/Documents/repos/tevinwang/vectordb-recipes/venv/lib/python3.10/site-packages/lance/vector.py", line 97, in vec_to_table
    ndim = _validate_ndim(values, ndim)
  File "/Users/tevinwang/Documents/repos/tevinwang/vectordb-recipes/venv/lib/python3.10/site-packages/lance/vector.py", line 35, in _validate_ndim
    raise ValueError(f"Expected {ndim} dimensions but got {len(v)} for {v}")
ValueError: Expected 512 dimensions but got 11 for StHAMY3_DZk
```

**Comment by rishabhRsinghvi** [comment]
@TevinWang please assign this to me.

**Comment by Nitish-Kshatriya-P** [comment]
Hey @TevinWang, can I take up this issue if it still exists?

**Comment by whitewooood** [comment]
I can take this. I’ll open a small PR to clarify the single-dictionary validation message for create_table/add.
