### ISSUE TITLE
bug: update openai-node version in lancedb node client

### ISSUE THREAD

**Issue by changhiskhan** [lancedb/lancedb#506]
Reported by user on discord:

```
Hello Mr. Chang. I am following the Embeddings tutorial (https://lancedb.github.io/lancedb/embedding/#applying-an-embedding-function). I am having this error:
TypeError: openai.Configuration is not a constructor
        at new OpenAIEmbeddingFunction (/opt/nodejs/node_modules/.pnpm/vectordb@0.2.5/node_modules/vectordb/dist/embedding/openai.js:37:31)
        at vectorization (/var/task/process/vectorization.js:14:23)
        at async Promise.allSettled (index 1)
        at async procesar_urls (/var/task/procesamiento.js:102:60)
        at async exports.handler (/var/task/index.js:37:35)

The code I use is:
const lancedb = require("vectordb");

const uri = process.env.S3_BUCKET_NAME;
const apiKey = process.env.OPENAI_API_KEY

/**
 
@param {Array} data [{uid, i, text_1}, {uid, i, text_2},...]
@returns
*/
async function vectorization (data) {

    const db = await lancedb.connect(uri);
    const embedding = new lancedb.OpenAIEmbeddingFunction('text', apiKey)
    const table = await db.createTable('vectors', data, embedding)

    const results = await table
        .search("Cómo funciona el algoritmo de Google?")
        .limit(10)
        .execute()

    console.log(results)
}


module.exports = {
    vectorization
}

I'm running it in Lambda.

Please could you give me some guide or idea of where the error could be or what I should do to fix it?
```

We are using OpenAI version 3 and the `Configuration` class disappeared entirely in version 4 (https://github.com/openai/openai-node/discussions/217)

**Comment by mathieugruson** [comment]
Hello, i face the same problem. So we need to stick to the openAi version 3 npm package such as openai@3.3.0 ?
