### ISSUE TITLE
`num_partitions` arg not being passed to `LanceTable` properly

### ISSUE THREAD

**Issue by prrao87** [lancedb/lancedb#526]
When testing ANN index construction on very small datasets (during debug phase), I'm setting the number of centroids to be 1 for the ANN index as per [this line of code](https://github.com/lancedb/lancedb/blob/d326146a403314528d36ad6a2cc8eed90b51f12b/python/lancedb/table.py#L179) in version `0.2.5` of LanceDB.

```py
tbl.create_index(metric="cosine", num_partitions=1, num_sub_vectors=4, vector_column_name="text")
```

However, these parameters aren't being passed to the `LanceTable` as can be seen in the error message below. What could be going wrong?

```sh
Traceback (most recent call last):
  File "/code/lancedb/index.py", line 157, in <module>
    main(tbl, data)
  File "/code/lancedb/index.py", line 120, in main
    tbl.create_index(metric="cosine", num_partitions=1, num_sub_vectors=4, vector_column_name="vector")
  File "/code/.venv/lib/python3.11/site-packages/lancedb/table.py", line 484, in create_index
    self._dataset.create_index(
  File "/code/.venv/lib/python3.11/site-packages/lance/dataset.py", line 694, in create_index
    self._ds.create_index(column, index_type, name, metric, kwargs)
OSError: LanceError(Index): KMeans: can not train 256 centroids with 100 vectors, choose a smaller K (< 100) instead
```

Not sure what an MRE would be in this case, but I presume you have a ton of simple examples you could try this out on your end on, so let me know if you need anything else to reproduce!

**Comment by prrao87** [comment]
When I change it to `num_partitions=500`, the index builds, but again, the actual number specified isn't being respected:

```sh
Sample 256 out of 500 to train kmeans of 384 dim, 1 clusters
```
