### ISSUE TITLE
Add support for metadata filtering only for nodejs

### ISSUE THREAD

**Issue by hammad-rb** [lancedb/lancedb#529]
As we see we can have a metadata filter(s) without providing search or vector to `search` for `python`
```
result = table.search().where("item == 'foo'").limit(2).to_df()
```
```
       vector item  price
0  [3.1, 4.1]  foo   10.0
```
but its not the case with `nodejs`
```
const query = await table.search().where("item != 'item foo'").limit(20).execute();
```
result in this error
```
/Users/path/Desktop/lancedb-test/node_modules/vectordb/dist/query.js:104
            const buffer = yield tableSearch.call(this._tbl, this);
                                             ^

TypeError: failed to downcast any to Array
    at Query.<anonymous> (/Users/path/Desktop/lancedb-test/node_modules/vectordb/dist/query.js:104:46)
    at Generator.next (<anonymous>)
    at /Users/path/Desktop/lancedb-test/node_modules/vectordb/dist/query.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/path/Desktop/lancedb-test/node_modules/vectordb/dist/query.js:17:12)
    at Query.execute (/Users/path/Desktop/lancedb-test/node_modules/vectordb/dist/query.js:97:16)
    at filterMetadata (file:///Users/path/Desktop/lancedb-test/lancedb_exists.js:35:78)

Node.js v18.16.0
```

**Comment by samlhuillier** [comment]
I am interested in this too! As far as I can tell it has not yet been implemented...

**Comment by snordgren** [comment]
I need this as well, I need to store two units of metadata: filename and last indexed at (so I don't need to re-index). It looks like it's JsQuery::js_search that needs to be modified, in the Rust code, this code in particular:

```rust
let query_vector = query_obj.get::<JsArray, _, _>(&mut cx, "_queryVector")?;
let query = convert::js_array_to_vec(query_vector.deref(), &mut cx);
```

Here, the need for an array is hardcoded, and the array must also be non-zero.

The Python lib instead has `LanceEmptyQueryBuilder` which is created when the `search()` function is ran with no vector.

```python
class LanceEmptyQueryBuilder(LanceQueryBuilder):
    def to_arrow(self) -> pa.Table:
        ds = self._table.to_lance()
        return ds.to_table(
            columns=self._columns,
            filter=self._where,
            limit=self._limit,
        )
```

Unfortunately, the `to_lance` and subsequent `to_table` code veers off into the Lance library, which doesn't seem to have a Node.js version, and then further into the pyarrow code, using pa.dataset.Scanner.

However! There is similar scanner code in the `execute` function of `Query` in the Rust code. Maybe an alternative path could be added here, which doesn't invoke scanner.nearest if the array is zero-length, alternatively, make the array an optional value. I don't know if it's enough to remove the `.nearest` call, at the very least limit would need to be supplemented if there is no nearest call.

```rust
    /// Execute the queries and return its results.
    ///
    /// # Returns
    ///
    /// * A [DatasetRecordBatchStream] with the query's results.
    pub async fn execute(&self) -> Result<DatasetRecordBatchStream> {
        let mut scanner: Scanner = self.dataset.scan();

        scanner.nearest(
            crate::table::VECTOR_COLUMN_NAME,
            &self.query_vector,
            self.limit,
        )?;
        scanner.nprobs(self.nprobes);
        scanner.use_index(self.use_index);
        self.select.as_ref().map(|p| scanner.project(p.as_slice()));
        self.filter.as_ref().map(|f| scanner.filter(f));
        self.refine_factor.map(|rf| scanner.refine(rf));
        self.metric_type.map(|mt| scanner.distance_metric(mt));
        Ok(scanner.try_into_stream().await?)
    }
```

There is a `limit` function in the Rust Scanner class, which could be applied to replace the limit in the `nearest` call if there is no query vector. As far as I can see - having never seen the Lance codebase before - that *should* be enough to support the no-vector query use case, if the Node.js Rust bindings are updated to accept an undefined `_queryVector`.

Am I missing something? Should I take a shot at implementing this?

**Comment by flaviut** [comment]
The docs say this can be done by just omitting the `.search()`: https://lancedb.github.io/lancedb/sql/#filtering-without-vector-search

```
> await tbl.filter("id = 10").limit(10).execute();
```
