### ISSUE TITLE
TypeError: Vector constructor expects an Array of Data instances.

### ISSUE THREAD

**Issue by samlhuillier** [lancedb/lancedb#621]
For this piece of typescript:
```
const testSchema = new Schema([
    new Field(
      "vector",
      new FixedSizeList(128, new Field("float32", new Float32()))
    ),
  ]);
  const newTable = await db.createTable({
    name: "vectors",
    schema: testSchema,
  });
```
I get the error: "TypeError: Vector constructor expects an Array of Data instances." With the following stack trace:
```
(node:5074) UnhandledPromiseRejectionWarning: TypeError: Vector constructor expects an Array of Data instances.
    at new Vector (/Users/sam/Desktop/vite-ragnote/node_modules/vectordb/node_modules/apache-arrow/vector.js:45:19)
    at /Users/sam/Desktop/vite-ragnote/node_modules/vectordb/node_modules/apache-arrow/table.js:80:50
    at Array.map (<anonymous>)
    at unwrap (/Users/sam/Desktop/vite-ragnote/node_modules/vectordb/node_modules/apache-arrow/table.js:80:39)
    at /Users/sam/Desktop/vite-ragnote/node_modules/vectordb/node_modules/apache-arrow/table.js:88:43
    at Array.flatMap (<anonymous>)
    at new Table (/Users/sam/Desktop/vite-ragnote/node_modules/vectordb/node_modules/apache-arrow/table.js:88:30)
    at createEmptyTable (/Users/sam/Desktop/vite-ragnote/node_modules/vectordb/dist/arrow.js:136:12)
    at LocalConnection.<anonymous> (/Users/sam/Desktop/vite-ragnote/node_modules/vectordb/dist/index.js:139:92)
    at Generator.next (<anonymous>)
```

Using the following:
- vectordb 0.3.5
- electron, react, vite template: https://github.com/electron-vite/electron-vite-react.git (lancedb code running in main process)
- macosx intel system

Any help would be greatly appreciated :)

**Comment by samlhuillier** [comment]
Fixed! Turns out the issue was with ensuring the version of apache-arrow for the project was the same as the one lancedb uses!
