### ISSUE TITLE
Issue with vectordb-win32-x64-msvc

### ISSUE THREAD

**Issue by samlhuillier** [lancedb/lancedb#630]
Hi! I get the following error on windows:
```
Error: vectordb: failed to load native library.
  You may need to run `npm install @lancedb/vectordb-win32-x64-msvc`.

  If that does not work, please file a bug report at https://github.com/lancedb/lancedb/issues

 Source error: Error: The specified module could not be found.
\\?\C:\Users\sam\Desktop\vite-ragnote\node_modules\@lancedb\vectordb-win32-x64-msvc\index.node
    at Object.<anonymous> (C:\Users\sam\Desktop\vite-ragnote\node_modules\vectordb\native.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\sam\Desktop\vite-ragnote\node_modules\vectordb\dist\query.js:28:25)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
```
Ran the manual install npm install @lancedb/vectordb-win32-x64-msvc along with node 16, 18 and 20. How can go about 
fixing this?

**Comment by wjones127** [comment]
Hi @samlhuillier.

I was unable to reproduce. I ran the following steps:

```shell
mkdir test
cd test
npm init
npm install vectordb
```

When I run `npm list --all`, I find the required library `@lancedb/vectordb-win32-x64-msvc@0.3.6` is already installed:

```
`-- vectordb@0.3.6
  +-- @apache-arrow/ts@12.0.1
  | +-- @types/command-line-args@5.2.0
  | +-- @types/command-line-usage@5.0.2
  ...
  +-- UNMET OPTIONAL DEPENDENCY @lancedb/vectordb-darwin-arm64@0.3.6
  +-- UNMET OPTIONAL DEPENDENCY @lancedb/vectordb-darwin-x64@0.3.6
  +-- UNMET OPTIONAL DEPENDENCY @lancedb/vectordb-linux-arm64-gnu@0.3.6
  +-- UNMET OPTIONAL DEPENDENCY @lancedb/vectordb-linux-x64-gnu@0.3.6
  +-- @lancedb/vectordb-win32-x64-msvc@0.3.6
  ...
```

And I can import this with:

```
> const vectordb = require("vectordb")
> vectordb
{
  Query: [Getter],
  OpenAIEmbeddingFunction: [Getter],
  connect: [Function: connect],
  LocalConnection: [class LocalConnection],
  LocalTable: [class LocalTable],
  WriteMode: { Create: 'create', Overwrite: 'overwrite', Append: 'append' },
  DefaultWriteOptions: [class DefaultWriteOptions],
  isWriteOptions: [Function: isWriteOptions],
  MetricType: { L2: 'l2', Cosine: 'cosine', Dot: 'dot' }
}
```

Can you share the exact steps you performed to reach this error?

**Comment by samlhuillier** [comment]
Ok interesting. I was running on windows server on a GCP instance and neither my electron app nor the code you suggest works. However, I just booted up a vmware windows vm and both work fine. Closing as likely a strange issue with windows server...Apologies for the bother.
