### ISSUE TITLE
Error when trying to open Fine on Macos

### ISSUE THREAD

**Issue by oscarandreazza** [lancedb/lancedb#652]
A Javascript error ocurred in the main process

Uncaught Exception:
Error: vectordb: failed to load native library.
You may need to run `npm install @lancedb/vectordb-darwin-x64`.

If that does not work, please file a bug report at https://github.com/lancedb/lancedb/issues

Source error: Error: Cannot find module '@lancedb/vectordb-darwin-x64'
Require stack:
- /Applications/Fine.app/Contents/Resources/app.asar/node_modules/vectordb/native.js
- /Applications/Fine.app/Contents/Resources/app.asar/node_modules/vectordb/dist/query.js
- /Applications/Fine.app/Contents/Resources/app.asar/node_modules/vectordb/dist/remote/index.js
- /Applications/Fine.app/Contents/Resources/app.asar/node_modules/vectordb/dist/index.js
- /Applications/Fine.app/Contents/Resources/app.asar/dist-electron/main/index.js
- 
at Object.<anonymous> (/Applications/Fine.app/Contents/Resources/app.asar/node_modules/vectordb/native.js:26:11)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Object..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at node:internal/modules/cjs/loader:967:12
at Function._load (node:electron/js2c/asar_bundle:2:13327)
at Module.require (node:internal/modules/cjs/loader:1150:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/Applications/Fine.app/Contents/Resources/app.asar/node_modules/vectordb/dist/query.js:28:25)
at Module._compile (node:internal/modules/cjs/loader:1271:14)

**Comment by oscarandreazza** [comment]
I installed it as recommended, but it didn't work.
`npm install @lancedb/vectordb-darwin-x64`

**Comment by changhiskhan** [comment]
I think we saw something similar with Electron apps. For those apps, you have to build the right module targeting the architecture. Is it possible that you built the app on apple silicon but are running it on an intel mac? I'm not super familiar with how fine.dev pulls native node modules
