### ISSUE TITLE
RuntimeError with LanceDB Cloud Version in FastAPI Environment

### ISSUE THREAD

**Issue by SeeknnDestroy** [lancedb/lancedb#680]
@AyushExel @fcakyon

## **Description**
We are experiencing a `RuntimeError` when integrating the cloud version of LanceDB with FastAPI using our custom `LanceDBVectorStore` class in the `autollm` package. This issue occurs specifically when switching from a local LanceDB setup to a cloud-based setup.  We have implemented the feature branch that supports cloud feature of `lancedb` via overwriting the llama-index class in this branch and worked from there: https://github.com/safevideo/autollm/tree/feature/lancedb-cloud-support

## **Relevant Details**
- Link to related issue: [Enhancement Request: Cloud Support in LanceDBVectorStore for Llama-Index #671](https://github.com/lancedb/lancedb/issues/671)
- The issue is encountered in a FastAPI environment.
- The `LanceDBVectorStore` class has been modified to support LanceDB's cloud version (referenced in the previous issue).
- The error does not occur with local LanceDB setup but only with the cloud setup.
- The cloud setup works fine outside the FastAPI environment, indicating the tables exist and are accessible.

## **Error Log**
```bash
INFO:     Started server process [49449]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
2023-12-04 18:22:06,735 - autollm - INFO - Embedding Token Usage: 6
ERROR:root:Table {name} does not exist.Please first call db.create_table({name}, data)
/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/lancedb/remote/db.py:105: RuntimeWarning: coroutine 'RestfulLanceDBClient.post' was never awaited
  logging.error(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
INFO:     127.0.0.1:33324 - "POST /query HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/autollm/auto/fastapi_app.py", line 105, in query
    response = query_engine.query(user_query)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/llama_index/core/base_query_engine.py", line 30, in query
    return self._query(str_or_query_bundle)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/llama_index/query_engine/retriever_query_engine.py", line 170, in _query
    nodes = self.retrieve(query_bundle)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/llama_index/query_engine/retriever_query_engine.py", line 126, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/llama_index/core/base_retriever.py", line 54, in retrieve
    nodes = self._retrieve(query_bundle)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 88, in _retrieve
    return self._get_nodes_with_embeddings(query_bundle)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/retriever.py", line 164, in _get_nodes_with_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/llama_index/vector_stores/lancedb.py", line 167, in query
    results = lance_query.to_df()
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/deprecation.py", line 260, in _inner
    return function(*args, **kwargs)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/lancedb/query.py", line 186, in to_df
    return self.to_pandas()
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/lancedb/query.py", line 195, in to_pandas
    return self.to_arrow().to_pandas()
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/lancedb/query.py", line 409, in to_arrow
    return self._table._execute_query(query)
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/lancedb/remote/table.py", line 165, in _execute_query
    return self._conn._loop.run_until_complete(result).to_arrow()
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/asyncio/base_events.py", line 625, in run_until_complete
    self._check_running()
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/asyncio/base_events.py", line 584, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

## **Expected Behavior**
The application should query the LanceDB cloud database without errors, similar to how it operates with the local database setup.

## **Environment**
- LanceDB version: 0.3.4
- FastAPI version: 0.104.1
- Llama-Index version: 0.9.10

## **Additional Context**
- The application functions correctly with a local LanceDB instance.
- The issue seems to be related to asynchronous operations in the FastAPI environment.

We are seeking guidance or a fix for this issue, as it is critical for our integration of LanceDB's cloud version in a FastAPI environment. Any insights or suggestions would be greatly appreciated.

Thank you for your attention to this matter.

**Comment by westonpace** [comment]
This problem will occur anytime the lancedb cloud client is used in an asynchronous environment.  Here is a minimal reproduction (you will need to supply a valid URL and API key):

```
import asyncio
# import nest_asyncio
import pyarrow as pa

import lancedb

async def main():
#     nest_asyncio.apply()
    db = lancedb.connect("db://****", api_key="****", region="us-east-1")

    if 'foo' not in db.table_names():
        data = pa.Table.from_pydict({
            "vector": pa.array([[1.1, 2.1, 3.1], [4.1, 5.1, 6.1], [-1.1, -2.1, -3.1]], pa.list_(pa.float32(), 3)),
            "x": [10, 4, 15]
        })
        db.create_table("foo", data)

    table = db.open_table("foo")
    scan = table.search([1, 2, 3]).limit(10).where('x > 7').nprobes(3)
    results = scan.to_df()
    print(results)

asyncio.run(main())
```

The root problem is that the dataset API is a synchronous API but under the hood we use aiohttp which is an asynchronous http library.  There is no great way to call asynchronous code from synchronous code in python.  We grab the current event loop and try to use that to run the asynchronous method.  However, if an asynchronous method is already in progress (e.g. from FastAPI) then this will fail with the given error (you cannot go async -> sync -> async because this is nested async).

The easiest workaround (which you can see commented out in the reproduction) is to use nest_asyncio.  We should probably add this in our documentation somewhere.

One potential solution would be to add an async API for lancedb but that won't help much in this case because llama-index is synchronous so it just pushes the problem up one level (it looks like llama-index has encountered this before and [has solved it with nest_asyncio](https://github.com/run-llama/llama_index/blob/main/llama_index/async_utils.py#L27))

Another solution would be for us to use something like unsync to run the aiohttp methods on a dedicated thread / event loop but that would be a more involved fix.

**Comment by eddyxu** [comment]
Another possibility is that we make async API to be the primary API in python.
