### ISSUE TITLE
[Bug]: TypeError, `RemoteTable.search()` missing 1 required positional argument: 'query'

### ISSUE THREAD

**Issue by SeeknnDestroy** [lancedb/lancedb#690]
### Issue Description:
**Summary**: Encountering a TypeError with the `db.open_table(lancedb_table_name).search()` method when using LanceDB's cloud option when I don't provide `query` parameter to remote search.

**Environment**:
- LanceDB Version: 0.3.4

**Steps to Reproduce**:
1. Initialize LanceDB with cloud configuration.
2. Call the `search()` method on a `RemoteTable` object without any arguments.

**Expected Behavior**:
The `search()` method should execute without errors, similar to the local LanceDB setup.

**Actual Behavior**:
Received a `TypeError` indicating a missing required positional argument: 'query'.

**Code Snippet**:
```python
import lancedb
from constants import DEFAULT_LANCEDB_SEARCH_LIMIT, LANCEDB_TABLE_NAME, LANCEDB_URI

lancedb_uri: str = LANCEDB_URI
lancedb_table_name: str = LANCEDB_TABLE_NAME
lancedb_api_key: str = os.getenv("LANCEDB_API_KEY")
lancedb_region: str = os.getenv("LANCEDB_REGION")

# Connect to LanceDB Cloud
db = lancedb.connect(lancedb_uri, api_key=lancedb_api_key, region=lancedb_region)

# Error occurs here
existing_document_ids = {
    item['document_id']
    for item in db.open_table(lancedb_table_name).search(" ").limit(DEFAULT_LANCEDB_SEARCH_LIMIT).select(
        ["document_id"]).to_list()
}
```

**Error Message**:
```
Traceback (most recent call last):
  File "path/to/script.py", line 33, in <module>
    for item in db.open_table(lancedb_table_name).search(" ").limit(DEFAULT_LANCEDB_SEARCH_LIMIT).select(
TypeError: RemoteTable.search() missing 1 required positional argument: 'query'
```

**Additional Context**:
- Same code works as expected with local LanceDB settings.
- The issue arises only when switched to LanceDB's cloud option.
- I want to be able to list the document id's of my all existing documents in LanceDB cloud.
- If I provide empty list as `.search(query="")` I am getting following error as well:

```
Traceback (most recent call last):
  File "/home/seekndestroy/safeVideo/github/ultralytics-docs-chat/testing.py", line 34, in <module>
    ["document_id"]).to_list()
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/lancedb/query.py", line 217, in to_list
    return self.to_arrow().to_pylist()
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/lancedb/query.py", line 397, in to_arrow
    vector = self._query if isinstance(self._query, list) else self._query.tolist()
AttributeError: 'str' object has no attribute 'tolist
```

**Potential Causes**:
It seems like the cloud version of `RemoteTable.search()` might require explicit query parameters, which differs from its local counterpart. This inconsistency leads to a `TypeError`.

**Request**:
I kindly request the LanceDB development team to look into this. Clarification on the expected behavior of listing all the existing documents in cloud or a fix would be greatly appreciated.

**Comment by AyushExel** [comment]
Thanks for reporting. Someone from the team should get to this.  
I've also been chatting with @fcakyon and I think a better approach for getting all the rows would be to simply call `table.to_list()`, `to_df()` etc. instead of doing an empty search.

**Comment by SeeknnDestroy** [comment]
Thanks @AyushExel,

I tried the `to_pandas method` but it seems it is not implemented yet:

```python
db = lancedb.connect(LANCEDB_URI, api_key=LANCEDB_API_KEY, region=LANCEDB_REGION)
table = db.open_table(LANCEDB_TABLE_NAME).

print(table.to_pandas())
```

Error:
```
to_pandas() is not supported on the LanceDB cloud
```

Also could not use directly `table.to_list()`:
```
Traceback (most recent call last):
    table.to_list()
AttributeError: 'RemoteTable' object has no attribute 'to_list'
```

Any insights?

**Comment by westonpace** [comment]
Hmm, does `None` work?  If it does then we should clean up the typing here because I think it's wrong for the `search` method.

```
db.open_table(lancedb_table_name).search(None).limit(DEFAULT_LANCEDB_SEARCH_LIMIT).select(
        ["document_id"]).to_list()
```

**Comment by SeeknnDestroy** [comment]
No @westonpace, it gave the following error:

```
Traceback (most recent call last):
    ["document_id"]).to_list()
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/lancedb/query.py", line 217, in to_list
    return self.to_arrow().to_pylist()
  File "/home/seekndestroy/mambaforge/envs/ultralytics/lib/python3.10/site-packages/lancedb/query.py", line 397, in to_arrow
    vector = self._query if isinstance(self._query, list) else self._query.tolist()
AttributeError: 'NoneType' object has no attribute 'tolist'
```

By the way I noticed that I mistyped the original error cause which should have been `db.open_table(lancedb_table_name).search()` instead of `.search(" ")` that caused the `RemoteTable.search() missing 1 required positional argument: 'query'` error. I was able to use the first one in my local lancedb settings, `RemoteTable` does not allow me to do so.

**Comment by westonpace** [comment]
Alright, I tried reproducing this myself and got the same error.  You are correct, this functionality is not yet supported.

**Comment by fcakyon** [comment]
We are using a temporary workaround @AyushExel suggested (we are grateful to him) but it would be better if this matter is handled in a more robust way :) @QianZhu

**Comment by QianZhu** [comment]
Thanks for submitting the issue. We are not supporting `to_pandas()` from SaaS RemoteTable. Will get back to you guys with our support on returning all the table rows using SaaS APIs.
