### ISSUE TITLE
bug(python): UnicodeError: label empty or too long error raised

### ISSUE THREAD

**Issue by westonpace** [lancedb/lancedb#799]
### What happened?

Running even a simple command such as `print(list(conn.table_names()))` would generate the following error:

```
Traceback (most recent call last):
  File "/home/pace/.pyenv/versions/3.11.3/lib/python3.11/encodings/idna.py", line 163, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pace/.cache/pypoetry/virtualenvs/myvenv/lib/python3.11/site-packages/lancedb/db.py", line 198, in __getitem__
    return self.open_table(name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pace/.cache/pypoetry/virtualenvs/myvenv/lib/python3.11/site-packages/lancedb/remote/db.py", line 106, in open_table
    self._loop.run_until_complete(
  File "/home/pace/.pyenv/versions/3.11.3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/pace/.cache/pypoetry/virtualenvs/myvenv/lib/python3.11/site-packages/lancedb/remote/client.py", line 142, in post
    async with self.session.post(
  File "/home/pace/.cache/pypoetry/virtualenvs/myvenv/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/pace/.cache/pypoetry/virtualenvs/myvenv/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pace/.cache/pypoetry/virtualenvs/myvenv/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pace/.cache/pypoetry/virtualenvs/myvenv/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pace/.cache/pypoetry/virtualenvs/myvenv/lib/python3.11/site-packages/aiohttp/connector.py", line 1173, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dclure/.cache/pypoetry/virtualenvs/training-data-knns-om8rbqrI-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 884, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pace/.cache/pypoetry/virtualenvs/myvenv/lib/python3.11/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pace/.pyenv/versions/3.11.3/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pace/.pyenv/versions/3.11.3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pace/.pyenv/versions/3.11.3/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

### Are there known steps to reproduce?

The root cause seems to have been a misconfigured URI.  So this may only be a "need a friendlier error message" problem

**Comment by Xuanwo** [comment]
Hi, this issue is invalid because the reported crash was caused by a misconfigured URI leading to DNS resolution failure (idna encoding error), not by a code defect in LanceDB. I'm closing this now. Feel free to create a new issue if the problem still exists.
