### ISSUE TITLE
bug(install Memex Desktop)

### ISSUE THREAD

**Issue by erikcestner** [lancedb/lancedb#854]
### LanceDB version

@lancedb/vectordb-darwin-x64@0.4.3

### What happened?

not shure if this is the right way to do this , I`m new to all this GutHub thing, basicly learning by making mistakes...
thx in advanced for tips and solutions

## Memex Desktop Error

 

> i downloaded Memex Desktop
>  i try to run Memex Desktop and get this Warning (Error Below)
> i downloaded Node and istalled @lancedb/vectordb-darwin-x64@0.4.3 
> relaunched Memex get the same warning

### Error:
Source error: Error: Cannot find module '@lancedb/vectordb-darwin-x64'
Require stack:
- /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/native.js
- /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/query.js
- /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/remote/index.js
- /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/index.js
at Object.<anonymous> (/Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/native.js:26:11)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at Module._load (node:internal/modules/cjs/loader:967:12)
at l._load (node:electron/js2c/asar_bundle:2:13642)
at Module.require (node:internal/modules/cjs/loader:1150:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/query.js:28:25)
at Module._compile (node:internal/modules/cjs/loader:1271:14)

i expect that the progam Memex Desktop works

### Are there known steps to reproduce?

Step by Step

- Visit: https://tutorials.memex.garden/tutorials/obsidian-and-logseq-sync
- went to : How to Activate the Sync [Download the sync helper](https://github.com/WorldBrain/memex-local-sync/releases/latest)
- downloaded Memex-Desktop-v0.0.48-mac-x64.dmg file
- installed the dmg file
- launched memex desktop then i get the Error message
- so i installed node (worked fine)
- if i check Terminal with npm version
> npm: '10.2.4',
  node: '20.11.0',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.20.1',
  base64: '0.5.1',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '8.1.1',
  modules: '115',
  napi: '9',
  nghttp2: '1.58.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.12+quic',
  simdutf: '4.0.4',
  tz: '2023c',
  undici: '5.27.2',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.19',
  v8: '11.3.244.8-node.17',
  zlib: '1.2.13.1-motley-5daffc7'

- opened terminal and typed : npm install @lancedb/vectordb-darwin-x64 , hit enter

Terminal showed this
> added 1 package in 8s
> npm notice 
> npm notice New minor version of npm available! 10.2.4 -> 10.3.0
> npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.3.0
> npm notice Run npm install -g npm@10.3.0 to update!
> npm notice 
> username@MacBook-Pro ~ % npm list | grep vectordb
> └── @lancedb/vectordb-darwin-x64@0.4.3

try to relauch Memex Desktop but got the same Error message

### Error:

> Source error: Error: Cannot find module '@lancedb/vectordb-darwin-x64'
> Require stack:
> - /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/native.js
> - /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/query.js
> - /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/remote/index.js
> - /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/index.js
> at Object.<anonymous> (/Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/native.js:26:11)
> at Module._compile (node:internal/modules/cjs/loader:1271:14)
> at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
> at Module.load (node:internal/modules/cjs/loader:1126:32)
> at Module._load (node:internal/modules/cjs/loader:967:12)
> at l._load (node:electron/js2c/asar_bundle:2:13642)
> at Module.require (node:internal/modules/cjs/loader:1150:19)
> at require (node:internal/modules/cjs/helpers:119:18)
> at Object.<anonymous> (/Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/query.js:28:25)
> at Module._compile (node:internal/modules/cjs/loader:1271:14)

followed the steps in Error message and here i am....
Thx for your Help

https://github.com/lancedb/lancedb/assets/157488652/d6615412-112d-4ecf-a7ff-6b32156eebe8

**Comment by Xuanwo** [comment]
Feel free to create a new issue if still exists
