### ISSUE TITLE
bug(node): Several bugs when trying to setup a simple use case

### ISSUE THREAD

**Issue by AbrahamLopez10** [lancedb/lancedb#882]
### LanceDB version

0.4.6

### What happened?

Hi, first of all many thanks for building LanceDB as it's an awesome and promising project.

I'd love to get LanceDB working so I have been trying to setup LanceDB locally in a new TypeScript project but I cannot get the simplest use case to work as I have encountered several bugs along with some DX issues:

1. When creating an empty table and passing an Apache Arrow `schema` I get this error:
> Vector constructor expects an Array of Data instances.

2. When creating the table with both a schema and a single row of sample data I get this other error:
> TypeError: RecordBatch constructor expects a [Schema, Data] pair.

  The only way I was able to get it working is by creating a table with no schema and some sample data, which is unfortunate as I'm forced to create a table with fake data that I then have to delete.

3. This is not a bug per se but just that the docs/examples might be outdated: 
- The `.createTable()` function currently requires a "props" object as parameter rather than individual function arguments as the docs/example show.
- The `.search()` function has the `query` parameter required so I'm forced to pass `undefined` if I want to retrieve all rows in order to do some SQL style filtering otherwise I get a "An argument for 'query' was not provided." type error, but the docs mention that I can just call `.search()` without parameters to do this.

4. If I try to do a search, either by passing `undefined` to retrieve all rows or a vector (e.g. [0, 0, 0, ...]) it fails with:
> No vector column found to create index

Below is the full code I made for this along with my notes on the issues experienced above.

If any clarification on the above is needed please let me know, I'd love to help in any way I can.

Thanks!

### Are there known steps to reproduce?

```ts
const vectorDb = await lancedb.connect("../data/lancedb/resources");
const dimensions = 768;

const schema = new Schema([
  new Field("resource_id", new Int32(), false),
  new Field(
    "vector",
    new FixedSizeList(dimensions, new Field("value", new Float64())),
    false
  ),
]);

const vectorTable = await vectorDb
  .openTable("resources")
  .catch(async () => {
    // Table doesn't exist, so create it
    return await vectorDb.createTable({
      // NOTE: The docs are outdated, as createTable() expects a "props" object, but the docs indicate that it expects individual function arguments.
      name: "resources",
      //schema /* NOTE: Passing only the `schema` (without `data`) results in this error: Vector constructor expects an Array of Data instances. {"service":"web","stack":"TypeError: Vector constructor expects an Array of Data instances.\n    at new Vector (/Users/admin/Documents/Projects/test/node_modules/apache-arrow/vector.js:44:19)\n    at /Users/admin/Documents/Projects/test/node_modules/apache-arrow/table.js:80:50\n    at Array.map (<anonymous>)\n    at unwrap (/Users/admin/Documents/Projects/test/node_modules/apache-arrow/table.js:80:39)\n    at /Users/admin/Documents/Projects/test/node_modules/apache-arrow/table.js:88:43\n    at Array.flatMap (<anonymous>)\n    at new Table (/Users/admin/Documents/Projects/test/node_modules/apache-arrow/table.js:88:30)\n    at createEmptyTable (/Users/admin/Documents/Projects/test/node_modules/vectordb/dist/arrow.js:300:12)\n    at LocalConnection.createTableImpl (/Users/admin/Documents/Projects/test/node_modules/vectordb/dist/index.js:130:88)\n    at LocalConnection.createTable (/Users/admin/Documents/Projects/test/node_modules/vectordb/dist/index.js:116:27)","timestamp":"2024-01-28 14:11:54"} */,
      data: [
        { resource_id: 0, vector: Array(dimensions).fill(0.1) },
      ] /* NOTE: Passing both `schema` and `data` results in this error: RecordBatch constructor expects a [Schema, Data] pair. {"service":"web","stack":"TypeError: RecordBatch constructor expects a [Schema, Data] pair.\n    at new RecordBatch (/Users/admin/Documents/Projects/test/node_modules/apache-arrow/recordbatch.js:38:27)\n    at alignBatch (/Users/admin/Documents/Projects/test/node_modules/vectordb/dist/arrow.js:292:12)\n    at /Users/admin/Documents/Projects/test/node_modules/vectordb/dist/arrow.js:295:57\n    at Array.map (<anonymous>)\n    at alignTable (/Users/admin/Documents/Projects/test/node_modules/vectordb/dist/arrow.js:295:42)\n    at fromRecordsToBuffer (/Users/admin/Documents/Projects/test/node_modules/vectordb/dist/arrow.js:225:17)\n    at async LocalConnection.createTableImpl (/Users/admin/Documents/Projects/test/node_modules/vectordb/dist/index.js:137:22)\n    at async LocalConnection.createTable (/Users/admin/Documents/Projects/test/node_modules/vectordb/dist/index.js:116:16)\n    at async eval (webpack-internal:///(api)/./src/resources/resource.service.ts:231:20)","timestamp":"2024-01-28 14:11:04"} */,
    });
  });

const existingVectors = await vectorTable
  // NOTE: Contrary to what's in the docs, .search() requires an argument, otherwise a type error occurrs: "An argument for 'query' was not provided."
  .search(undefined)
  .where(`resource_id = ${resourceId}`)
  .limit(1)
  .execute();

if (existingVectors.length > 0) {
  console.log("existingVectors");
  await vectorTable.update({
    values: {
      vector: Array(dimensions).fill(1.1),
    },
    where: `resource_id = ${resourceId}`,
  }); // this works fine
} else {
  console.log("created vectors");
  await vectorTable.add([
    {
      resource_id: resourceId,
      vector: Array(dimensions).fill(0.2),
    },
  ]); // this works fine
}

// NOTE: I cannot get this to work, it seems to be always failing. Passing a vector (e.g. [0, 0, 0...]) instead of undefined also fails.
const matchedVectors = await vectorTable.search(undefined).execute();
/* error: LanceDBError: No vector column found to create index {"service":"test","stack":"Error: LanceDBError: No vector column found to create index","timestamp":"2024-01-28 14:12:53"} */

console.log(
  "matchedVectors:",
  matchedVectors.map((x) => x.resource_id)
);
```

**Comment by eddyxu** [comment]
@AbrahamLopez10 thanks for reporting these issues.

> When creating an empty table and passing an Apache Arrow schema I get this error:
> Vector constructor expects an Array of Data instances.

This is due to that you have two (potentially different) `apache-arrow` installed by vectordb and your package. 
Could you check apache arrow is the same 14.0.2 in your package.json?

I am looking at the rest of the issues and will keep you posted.

**Comment by AbrahamLopez10** [comment]
Thanks for the quick response! Yes, I forgot to mention it but I made sure that the Apache Arrow version I'm using (v14.0.2) was the same that comes with the v0.4.6 version of the `vectordb` NPM package that I'm using.

**Comment by AbrahamLopez10** [comment]
Thanks for the quick response! Yes, I forgot to mention it but I made sure that the Apache Arrow version I'm using (v14.0.2) was the same that comes with the v0.4.6 version of the `vectordb` NPM package that I'm using.

I realized this because I was getting typing errors when I installed the Apache Arrow dependency at first, which installed the latest version, so I downgraded to the matching version and the typing errors went again, so in theory using the matching version shouldn't cause these issues?

**Comment by eddyxu** [comment]
Update

* We have fixed the quickstart `createIndex` and `createTable` examples
* #757 
* I will work on the rest of this ticket this week.

**Comment by AbrahamLopez10** [comment]
@eddyxu Awesome, I'll stay tuned. For the time being, I also updated the JS/TS example in the README based on my report above:
https://github.com/lancedb/lancedb/pull/898

**Comment by andrao** [comment]
@AbrahamLopez10 I ran into the same issue with `Vector constructor expects an Array of Data instances`.

It throws from `instanceof` checks executed within the _apache-arrow_ package [0]. The problem is that instances of the classes exported from _@apache-arrow/ts_ **do not satisfy** `instanceof` checks run from within the non-TS _apache-arrow_ package. It's the latter to which calls are routed.

This is to say that a `Schema` instance from _@apache-arrow/ts_ isn't recognized as a `Schema` instance from _apache-arrow_ (nor is a `Table`, nor a `Field`, nor a `Utf8`, etc.).

The fix is to use the _apache-arrow_ package rather than _@apache-arrow/ts_. But then it's untyped! Unless you type cast. I set up a separate file to export classes that are both runtime-safe and type-safe:

```ts
import type * as ArrowTS from '@apache-arrow/ts';
import * as Arrow from 'apache-arrow'; // or: `const Arrow = require('apache-arrow');`

/**
 * @todo Export all necessary classes
 */
export const Bool = Arrow.Bool as typeof ArrowTS.Bool;
export const Date_ = Arrow.Date_ as typeof ArrowTS.Date_;
export const Field = Arrow.Field as typeof ArrowTS.Field;
export const FixedSizeList = Arrow.FixedSizeList as typeof ArrowTS.FixedSizeList;
export const Float = Arrow.Float as typeof ArrowTS.Float;
export const Schema = Arrow.Schema as typeof ArrowTS.Schema;
export const Utf8 = Arrow.Utf8 as typeof ArrowTS.Utf8;
```

This does the trick. For me, at least. 

---
[0] e.g. in _node_modules/apache-arrow/recordbatch.js,_ or _node_modules/apache-arrow/visitor/typecomparator.js_

**Comment by hazelnutcloud** [comment]
`apache-arrow` really should be a peer dependency or reexported by `vectordb`

**Comment by westonpace** [comment]
> apache-arrow really should be a peer dependency or reexported by vectordb

Yeah, I think peer dependency is a good idea, though it is potentially a breaking change.

Re-export would be kind of annoying if users are using arrow elsewhere because they need to still switch from other-schema to vectordb-schema and switching over the data types is kind of cumbersome.

Longer term it might be nice to update arrow-js so it either doesn't use instanceof or it adds hasinstance capabilities to schema/field/vector/etc.

**Comment by hazelnutcloud** [comment]
After testing the search function, I noticed that passing anything other than an array with a single number in it fails. Otherwise, it just returns everything from a table.

**Comment by westonpace** [comment]
> After testing the search function, I noticed that passing anything other than an array with a single number in it fails. Otherwise, it just returns everything from a table.

This sounds like a different issue.  Can you open up a new ticket with some kind of example?

The search function will expect an array.  The number of items that are in the array should match the dimension of the column you are retrieving.  So if you created the table where your vector column was arrays of size 1 then you would need to search it with an array of size 1.

**Comment by homerjam** [comment]
I'm experiencing all of the issues raised in this ticket - it seems as though search isn't working at all (and it was a bit painful to get to that point!).

I hope some time can be spent on the JS part of this very promising project : )

**Comment by Xuanwo** [comment]
Hi, this issue is invalid because the reported Node SDK failures were already fixed: apache-arrow is now a peer dependency with foreign-schema sanitization, the docs examples were updated, and the reported scenarios could not be reproduced on current versions (the cross-version Arrow conversion suite of 168 tests passes). I'm closing this now. Feel free to create a new issue if the problem still exists.
