### ISSUE TITLE
bug(python): Error when trying to search vectors with an index

### ISSUE THREAD

**Issue by pshashk** [lancedb/lancedb#928]
### LanceDB version

v0.5.3

### What happened?

`:assertion failed: sub_vector_idx < num_sub_vectors` when trying to search vectors with an index. 

### Are there known steps to reproduce?

```python
import lancedb
import numpy as np

rng = np.random.default_rng()

db = lancedb.connect("test")

data = [
    {"vector": rng.standard_normal(size=512, dtype="float32")} for _ in range(5_000)
]

tbl = db.create_table(
    "test",
    data=data,
)
tbl.create_index(
    num_partitions=256,
    num_sub_vectors=96,
    metric="dot",
)

tbl.search(rng.standard_normal(size=512, dtype="float32")).limit(1).to_list()
```
```
thread 'lance-cpu' panicked at /home/runner/work/lance/lance/rust/lance-index/src/vector/pq.rs:124:5:
assertion failed: sub_vector_idx < num_sub_vectors
thread 'lance_background_thread' panicked at /home/runner/work/lance/lance/rust/lance/src/utils/tokio.rs:34:24:
called `Result::unwrap()` on an `Err` value: RecvError(())
thread 'lance-cpu' panicked at /home/runner/work/lance/lance/rust/lance-index/src/vector/pq.rs:124:5:
assertion failed: sub_vector_idx < num_sub_vectors
thread 'Traceback (most recent call last):
lance-cpu' panicked at /home/runner/work/lance/lance/rust/lance-index/src/vector/pq.rs:124:5  File "<stdin>", line 1, in <module>
:
thread 'assertion failed: sub_vector_idx < num_sub_vectorslance-cpu
' panicked at /home/runner/work/lance/lance/rust/lance-index/src/vector/pq.rs:124:5:
assertion failed: sub_vector_idx < num_sub_vectors
thread 'lance-cpu' panicked at /home/runner/work/lance/lance/rust/lance-index/src/vector/pq.rs:124:5:
assertion failed: sub_vector_idx < num_sub_vectors
thread 'lance-cpu' panicked at /home/runner/work/lance/lance/rust/lance-index/src/vector/pq.rs:thread '124lance-cpu:' panicked at 5/home/runner/work/lance/lance/rust/lance-index/src/vector/pq.rs:
:assertion failed: sub_vector_idx < num_sub_vectors
124:5:
assertion failed: sub_vector_idx < num_sub_vectors
  File "/usr/local/lib/python3.10/dist-packages/lancedb/query.py", line 268, in to_list
    return self.to_arrow().to_pylist()
  File "/usr/local/lib/python3.10/dist-packages/lancedb/query.py", line 500, in to_arrow
    return self._table._execute_query(query)
  File "/usr/local/lib/python3.10/dist-packages/lancedb/table.py", line 1304, in _execute_query
    return ds.to_table(
  File "/usr/local/lib/python3.10/dist-packages/lance/dataset.py", line 397, in to_table
    ).to_table()
  File "/usr/local/lib/python3.10/dist-packages/lance/dataset.py", line 1883, in to_table
    return self.to_reader().read_all()
  File "pyarrow/ipc.pxi", line 757, in pyarrow.lib.RecordBatchReader.read_all
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
OSError: Io error: Execution error: External error: Execution error: ExecNode(Take): thread panicked: task 16974 panicked
```

**Comment by chebbyChefNEQ** [comment]
Hi @pshashk, `num_sub_vectors` should be set to an interget that divides the number of dimensions. I'm not sure why the safety check didn't trigger in your case. Could you try changing `num_sub_vectors` to something like `64`.

ps: your `num_partitions` is also a bit too large. Usually you want to shoot for `num_rows // 5000` ish (depending on the number of dimensions in your embedding vectors.

**Comment by pshashk** [comment]
@chebbyChefNEQ Thanks a lot! That solves the issue.

**Comment by KyleNewman97** [comment]
Hi @chebbyChefNEQ. I was also seeing the same issue when using `lancedb v0.5.3`. I created an index with `num_sub_vectors = 96`  but my original vector size was `512`. I only got the assertion error at `search` time and not during index creation.

Changing `num_sub_vectors` to 64 fixed the issue though. Thanks 😊
