### ISSUE TITLE
bug(node): windows 11 vectordb-win32-x64-msvc\index.node cannot be opened

### ISSUE THREAD

**Issue by samlhuillier** [lancedb/lancedb#939]
### LanceDB version

v0.4.8

### What happened?

This error happens on a windows 11 machine:
```
Error: vectordb: failed to load native library.
  You may need to run `npm install @lancedb/vectordb-win32-x64-msvc`.

  If that does not work, please file a bug report at https://github.com/lancedb/lancedb/issues

 Source error: Error: The specified module could not be found.
\\?\C:\Users\sam\Desktop\vite-ragnote\node_modules\@lancedb\vectordb-win32-x64-msvc\index.node
    at Object.<anonymous> (C:\Users\sam\Desktop\vite-ragnote\node_modules\vectordb\native.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\sam\Desktop\vite-ragnote\node_modules\vectordb\dist\query.js:28:25)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
```

npm list --all shows:
```
+-- @lancedb/vectordb-win32-x64-msvc@0.4.8
`-- vectordb@0.4.8
  +-- @apache-arrow/ts@14.0.2
  | +-- @types/command-line-args@5.2.0
  | +-- @types/command-line-usage@5.0.2
  | +-- @types/node@20.3.0
  | +-- @types/pad-left@2.1.1
  | +-- command-line-args@5.2.1
  | | +-- array-back@3.1.0
  | | +-- find-replace@3.0.0
  | | | `-- array-back@3.1.0 deduped
  | | +-- lodash.camelcase@4.3.0
  | | `-- typical@4.0.0
  | +-- command-line-usage@7.0.1
  | | +-- array-back@6.2.2
  | | +-- chalk-template@0.4.0
  | | | `-- chalk@4.1.2
  | | |   +-- ansi-styles@4.3.0
  | | |   | `-- color-convert@2.0.1
  | | |   |   `-- color-name@1.1.4
  | | |   `-- supports-color@7.2.0
  | | |     `-- has-flag@4.0.0
  | | +-- table-layout@3.0.2
  | | | +-- @75lb/deep-merge@1.1.1
  | | | | +-- lodash.assignwith@4.2.0
  | | | | `-- typical@7.1.1
  | | | +-- array-back@6.2.2
  | | | +-- command-line-args@5.2.1 deduped
  | | | +-- command-line-usage@7.0.1 deduped
  | | | +-- stream-read-all@3.0.1
  | | | +-- typical@7.1.1
  | | | `-- wordwrapjs@5.1.0
  | | `-- typical@7.1.1
  | +-- flatbuffers@23.5.26
  | +-- json-bignum@0.0.3
  | +-- pad-left@2.1.0
  | | `-- repeat-string@1.6.1
  | `-- tslib@2.6.2
  +-- UNMET OPTIONAL DEPENDENCY @lancedb/vectordb-darwin-arm64@0.4.8
  +-- UNMET OPTIONAL DEPENDENCY @lancedb/vectordb-darwin-x64@0.4.8
  +-- UNMET OPTIONAL DEPENDENCY @lancedb/vectordb-linux-arm64-gnu@0.4.8
  +-- UNMET OPTIONAL DEPENDENCY @lancedb/vectordb-linux-x64-gnu@0.4.8
  +-- @lancedb/vectordb-win32-x64-msvc@0.4.8 deduped
  +-- @neon-rs/load@0.0.74
  +-- apache-arrow@14.0.2
  | +-- @types/command-line-args@5.2.0 deduped
  | +-- @types/command-line-usage@5.0.2 deduped
  | +-- @types/node@20.3.0 deduped
  | +-- @types/pad-left@2.1.1 deduped
  | +-- command-line-args@5.2.1 deduped
  | +-- command-line-usage@7.0.1 deduped
  | +-- flatbuffers@23.5.26 deduped
  | +-- json-bignum@0.0.3 deduped
  | +-- pad-left@2.1.0 deduped
  | `-- tslib@2.6.2 deduped
  `-- axios@1.6.7
    +-- follow-redirects@1.15.5
    +-- form-data@4.0.0
    | +-- asynckit@0.4.0
    | +-- combined-stream@1.0.8
    | | `-- delayed-stream@1.0.0
    | `-- mime-types@2.1.35
    |   `-- mime-db@1.52.0
    `-- proxy-from-env@1.1.0
```

### Are there known steps to reproduce?

1. Fresh Windows 11 machine
2. npm init
3. npm install vectordb
4. const vectordb = require('vectordb')
5. node index.js

The error above appears.

The only solution I have found is that after installing visual studio and the c++ dev libraries it installs, does it work. This isn't optimal for me as I'm working in the context of an Electron app.

**Comment by chebbyChefNEQ** [comment]
hmmm this smells like we are dynamically linking these libraries. Will take a look

**Comment by samlhuillier** [comment]
Yes I suspect it's something along those lines. Thanks for taking a look

**Comment by samlhuillier** [comment]
Any updates on this @chebbyChefNEQ ?

**Comment by changhiskhan** [comment]
@samlhuillier we released a new version yesterday with statically linked lib. I cross commented on your issue. Can you give the new version a try?
