### ISSUE TITLE
bug(python): Error while running compaction

### ISSUE THREAD

**Issue by nairajay2k** [lancedb/lancedb#946]
### What happened?

Traceback (most recent call last):
  File "statlance.py", line 17, in <module>
    table.compact_files()
  File "/home/ubuntu/qdrant_datastore/venv/lib/python3.8/site-packages/lancedb/table.py", line 1239, in compact_files
    return self.to_lance().optimize.compact_files(*args, **kwargs)
  File "/home/ubuntu/qdrant_datastore/venv/lib/python3.8/site-packages/lance/dataset.py", line 1875, in compact_files
    return Compaction.execute(self._dataset, opts)
OSError: LanceError(IO): Execution error: Row ids did not arrive in sorted order: integers are ordered up to the 0th element, /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/convert/mod.rs:757:9

### Are there known steps to reproduce?

This table has 260 Million records of 1024 dim vector and payload. Im not sure if its feasible to share the dataset

**Comment by QianZhu** [comment]
related to https://github.com/lancedb/lancedb/issues/1498. Fixed.
