### ISSUE TITLE
bug(node): dynamic linking to lzma library on MacOS

### ISSUE THREAD

**Issue by billmoseley23** [lancedb/lancedb#956]
### What happened?

Uncaught Exception:
Error: vectordb: failed to load native library.
You may need to run `npm install @lancedb/vectordb-darwin-arm64`.

If that does not work, please file a bug report at https://github.com/lancedb/lancedb/issues

Source error: Error: dlopen(/Applications/Reor.app/Contents/Resources/app.asar.unpacked/node_modules/@lancedb/vectordb-darwin-arm64/index.node, 0x0001): Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
Referenced from: <84349C78-366A-35F8-8798-808072CCD3D8> /Applications/Reor.app/Contents/Resources/app.asar.unpacked/node_modules/@lancedb/vectordb-darwin-arm64/index.node
Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file)
at Object.<anonymous> (/Applications/Reor.app/Contents/Resources/app.asar/node_modules/vectordb/native.js:26:11)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at Module._load (node:internal/modules/cjs/loader:967:12)
at c._load (node:electron/js2c/node_init:2:13672)
at Module.require (node:internal/modules/cjs/loader:1150:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/Applications/Reor.app/Contents/Resources/app.asar/node_modules/vectordb/dist/query.js:19:25)
at Module._compile (node:internal/modules/cjs/loader:1271:14)

### Are there known steps to reproduce?

install on M1 Mac and run the app

**Comment by changhiskhan** [comment]
i *think* this a known issue with dynamically linking. @wjones127 was working on statically linking the dependency.

**Comment by wjones127** [comment]
This should be a quick fix. Need to do the same thing we did in pylance.
