### ISSUE TITLE
Error: vectordb: failed to load native library

### ISSUE THREAD

**Issue by TurboTomNL** [lancedb/lancedb#972]
### LanceDB version

@lancedb/vectordb-darwin-arm64@0.4.9

### What happened?

I get this error message. I tried the suggested solution: npm install @lancedb/vectordb-darwin-arm64. That ran correctly, but didn't solve the problem. This is the complete error message:

A JavaScript error occurred in the main process
Uncaught Exception:
Error: vectordb: failed to load native library.
You may need to run `npm install @lancedb/vectordb-darwin-arm64`.

If that does not work, please file a bug report at https://github.com/lancedb/lancedb/issues

Source error: Error: [dlopen(/Applications/Reor.app/Contents/Resources/app.asar.unpacked/node_modules/@lancedb/vectordb-darwin-arm64/index.node,](mailto:dlopen(/Applications/Reor.app/Contents/Resources/app.asar.unpacked/node_modules/@lancedb/vectordb-darwin-arm64/index.node,) 0x0001): Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
Referenced from: <84349C78-366A-35F8-8798-808072CCD3D8> [/Applications/Reor.app/Contents/Resources/app.asar.unpacked/node_modules/@lancedb/vectordb-darwin-arm64/index.node](mailto:/Applications/Reor.app/Contents/Resources/app.asar.unpacked/node_modules/@lancedb/vectordb-darwin-arm64/index.node)
Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file)
at Object.<anonymous> (/Applications/Reor.app/Contents/Resources/app.asar/node_modules/vectordb/native.js:26:11)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at Module._load (node:internal/modules/cjs/loader:967:12)
at c._load (node:electron/js2c/node_init:2:13672)
at Module.require (node:internal/modules/cjs/loader:1150:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/Applications/Reor.app/Contents/Resources/app.asar/node_modules/vectordb/dist/query.js:19:25)
at Module._compile (node:internal/modules/cjs/loader:1271:14)

### Are there known steps to reproduce?

I tried the suggested solution: npm install @lancedb/vectordb-darwin-arm64. That ran correctly, but didn't solve the problem.
Reinstalling reor didn't help.

**Comment by changhiskhan** [comment]
can you try again on the latest version? https://github.com/lancedb/lancedb/releases/tag/v0.4.10

v0.4.10 should fix the lzma issue

**Comment by TurboTomNL** [comment]
Hi, thanks for your quick response. How can I install that specific version?

**Comment by changhiskhan** [comment]
ok hang on tight, we had a release job failure. Once that's fixed it should just upload to npm

**Comment by wjones127** [comment]
This should now be fixed in the latest version. Try re-installing https://github.com/lancedb/lancedb/releases/tag/v0.4.10

**Comment by changhiskhan** [comment]
@TurboTomNL did the new release work for you?

**Comment by TurboTomNL** [comment]
@changhiskhan  hi, I've no idea how to install that specific version. I basically did the same as in my original message but unfortuntely also with the same result...

**Comment by malikalimoekhamedov** [comment]
I experience the same issue with version 0.10.0.

**Comment by Xuanwo** [comment]
Hi, this issue is invalid because the native library load failure was already fixed in v0.4.10: the 0.4.10+ binaries no longer reference the absolute /opt/homebrew/opt/xz/lib/liblzma.5.dylib load path, and lzma is now statically linked. I'm closing this now. Feel free to create a new issue if the problem still exists.
